import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
function statement(query,args=[]){return {bind(...values){return statement(query,values)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}}}
globalThis.testDb={prepare:statement,async batch(stmts){sql.exec('BEGIN');try{const rows=[];for(const s of stmts)rows.push(await s.all());sql.exec('COMMIT');return rows}catch(e){sql.exec('ROLLBACK');throw e}}};
const url=code=>'data:text/javascript;base64,'+Buffer.from(code).toString('base64');
const transpile=path=>ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const helpers=url(transpile('lib/measurement.ts'));
const mock=url(`export const authorize=()=>{};export const database=()=>globalThis.testDb;export const invalid=(error,status=400)=>Response.json({error},{status});export const failure=e=>{console.error(e);return Response.json({error:String(e)},{status:503})}`);
const permissionHelpers=url(transpile('lib/permissions.ts'));
const userMock=url("export const requireUser=async()=>({id:'test-admin',active:true,role:'admin',permissions:[]})");
const api=await import(url(transpile('app/api/data/route.ts').replace("'zod'",JSON.stringify(import.meta.resolve('zod'))).replace("'@/db/access'",JSON.stringify(mock)).replace("'@/lib/measurement'",JSON.stringify(helpers)).replace("'@/lib/permissions'",JSON.stringify(permissionHelpers)).replace("'@/db/users'",JSON.stringify(userMock))));
async function request(method,body,status=200){if(body?.kind==='measurements'&&body.data?.stageId&&body.data.allocations===undefined){const st=sql.prepare('SELECT * FROM stages WHERE id=?').get(body.data.stageId);if(st){const prior=sql.prepare('SELECT COALESCE(SUM(COALESCE(amountUnits,amountCents*100)),0) AS amount FROM measurements WHERE stageId=? AND date<? AND cancelledAt IS NULL').get(st.id,body.data.periodStart||'');const base=st.contractUnits??(st.contractCents||0)*100,amount=body.data.measurementInput==='amount'?Math.round(body.data.measurementValue*100)*100:Math.max(0,Math.round(base/100*body.data.percent/100)*100-prior.amount);body={...body,data:{...body.data,allocations:[{name:'MA3',amountUnits:amount},{name:'ALEX',amountUnits:0},{name:'Pedreiro',amountUnits:0}]}}}}const r=await api[method](new Request('http://localhost/api/data',{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}));const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d}
const create=(kind,data,status=201)=>request('POST',{kind,data},status);
const project=await create('projects',{name:'Obra teste',client:'Cliente',address:'Local',engineerId:null,start:'2026-01-01',end:'2026-12-31',budget:1000.12,status:'Em andamento',notes:''});
await create('projects',{name:'Orçamento inválido',client:'Cliente',address:'Local',engineerId:null,start:'2026-01-01',end:'2026-12-31',budget:1.001,status:'Em andamento',notes:''},400);
let data=await request('GET');assert.equal(data.projects.find(p=>p.id===project.id).budget,1000.12);assert.equal(sql.prepare('SELECT budgetUnits FROM projects WHERE id=?').get(project.id).budgetUnits,10001200);assert.equal(data.stages.length,9);assert.deepEqual(new Set(data.stages.map(s=>s.name)),new Set(['FUNDAÇÃO','TIJOLAMENTO','PILAR','LAJE CONCRETADA','TELHADO','REBOCO','PISO','CONTRA PISO','CORTE PAREDE']));
await request('POST',{action:'initialize'});assert.equal((await request('GET')).stages.length,9);
const stage=data.stages[0];
const edit=(value=1000.01)=>request('PATCH',{kind:'stages',id:stage.id,data:{...stage,name:'FUNDAÇÃO TESTE',contractor:'Empreiteira A',contractValue:value}});
const measure=(percent,previousId='',date='2026-09-01',periodStart=date,requestId=crypto.randomUUID())=>({requestId,stageId:stage.id,percent,previousId,date,periodStart,notes:'Verificação'});
await create('measurements',measure(30),400);
await edit();
const firstInput=measure(30);const first=await create('measurements',firstInput);await create('measurements',firstInput,200);
data=await request('GET');let m=data.measurements.find(m=>m.id===first.id);assert.equal(m.startBp,0);assert.equal(m.endBp,3000);assert.equal(m.startP4,0);assert.equal(m.endP4,300000);assert.equal(m.amountCents,30000);assert.equal(m.amountUnits,3000000);assert.equal(m.contractCents,100001);assert.equal(m.contractUnits,10000100);
await create('measurements',measure(101,first.id),400);await create('measurements',measure(29,first.id),400);await create('measurements',measure(30.00001,first.id),400);await create('measurements',measure(45,''),409);await create('measurements',measure(45,first.id,'2026-09-02','2026-09-01'),400);
const second=await create('measurements',measure(45,first.id,'2026-09-02'));
data=await request('GET');m=data.measurements.find(m=>m.id===second.id);assert.equal(m.startBp,3000);assert.equal(m.endBp,4500);assert.equal(m.startP4,300000);assert.equal(m.endP4,450000);assert.equal(m.amountCents,15000);assert.equal(m.amountUnits,1500000);
await request('DELETE',{id:first.id},400);
await request('PATCH',{kind:'stages',id:stage.id,data:{...stage,contractor:'A',contractValue:2000}},400);
await request('PATCH',{action:'payment',id:second.id,paid:true,paidAt:'2026-09-01',revision:0},400);
await request('PATCH',{action:'payment',id:second.id,paid:true,paidAt:'2026-09-03',revision:0});
await request('PATCH',{action:'payment',id:second.id,paid:false,paidAt:null,revision:0},409);
await request('DELETE',{id:second.id},400);
await request('PATCH',{action:'payment',id:second.id,paid:false,paidAt:null,revision:1});
data=await request('GET');m=data.measurements.find(m=>m.id===second.id);assert.equal(JSON.parse(m.paymentHistory).length,2);
await request('DELETE',{id:second.id});data=await request('GET');assert.ok(data.measurements.find(m=>m.id===second.id).cancelledAt);
const final=await create('measurements',measure(100,first.id,'2026-09-03'));data=await request('GET');assert.equal(data.measurements.filter(m=>!m.cancelledAt).reduce((t,m)=>t+m.amountUnits,0),10000100);
await create('measurements',measure(100,final.id,'2026-09-04'),400);
const {weekRange,normalizeMeasurements}=await import(helpers);assert.deepEqual(weekRange('2027-01-01'),{start:'2026-12-28',end:'2027-01-03'});
const legacy=normalizeMeasurements([{id:'legacy',name:'Legado',quantity:10,price:25}],[{id:'a',stageId:'legacy',date:'2026-01-01',quantity:2,unitPrice:25},{id:'b',stageId:'legacy',date:'2026-01-02',quantity:3,unitPrice:25}]);assert.equal(legacy[1].endP4,500000);assert.equal(legacy[1].amountUnits,750000);
assert.equal(data.stageTypes.length,9);
const customType=await create('stageTypes',{name:'Impermeabilização',description:'Proteção contra umidade'});
await create('stageTypes',{name:'  impermeabilizacao  ',description:''},409);
await create('stageTypes',{name:' ',description:''},400);
await request('PATCH',{kind:'stageTypes',id:customType.id,data:{name:'Impermeabilização de laje',description:'Manta e proteção mecânica'}});
const customStage=await create('stages',{projectId:project.id,stageTypeId:customType.id,name:'Laje de cobertura',contractValue:800,contractor:'Empreiteira A',start:'2026-09-01',end:'2026-09-30'});
const amountStage=await create('stages',{projectId:project.id,stageTypeId:customType.id,name:'Valor monetário oficial',contractValue:4800,contractor:'Empreiteira A',start:'2026-09-01',end:'2026-10-31'});
const amountFirst=await create('measurements',{requestId:crypto.randomUUID(),stageId:amountStage.id,percent:41.67,previousId:'',periodStart:'2026-09-01',date:'2026-09-07',notes:'Primeiro período'});
const amountSecondInput={requestId:crypto.randomUUID(),stageId:amountStage.id,percent:62.5033,measurementInput:'amount',measurementValue:1000,previousId:amountFirst.id,periodStart:'2026-09-08',date:'2026-09-14',notes:'Valor digitado'};
const amountSecond=await create('measurements',amountSecondInput);let amountStored=sql.prepare('SELECT * FROM measurements WHERE id=?').get(amountSecond.id);assert.equal(amountStored.amountUnits,10000000);assert.equal(amountStored.endP4,625033);
await create('measurements',amountSecondInput,200);
await request('PATCH',{kind:'measurements',id:amountSecond.id,revision:0,data:{...amountSecondInput,measurementValue:999.9999,percent:62.5033,allocations:[{name:'MA3',amountUnits:10000000},{name:'ALEX',amountUnits:0},{name:'Pedreiro',amountUnits:0}]}},400);
await request('PATCH',{kind:'measurements',id:amountSecond.id,revision:0,data:{...amountSecondInput,measurementValue:1000,allocations:[{name:'MA3',amountUnits:5000000},{name:'ALEX',amountUnits:3000000},{name:'Pedreiro',amountUnits:2000000}]}});amountStored=sql.prepare('SELECT * FROM measurements WHERE id=?').get(amountSecond.id);assert.equal(amountStored.amountUnits,10000000);assert.deepEqual(JSON.parse(amountStored.allocations).map(r=>r.amountUnits),[5000000,3000000,2000000]);
const precisionStage=await create('stages',{projectId:project.id,stageTypeId:customType.id,name:'Bases por empresa',contractValue:1234.56,alexValue:300.12,pedreiroValue:200.34,contractor:'Empreiteira A',start:'2026-09-01',end:'2026-09-30'});const precisionRow=sql.prepare('SELECT * FROM stages WHERE id=?').get(precisionStage.id);assert.equal(precisionRow.contractUnits,12345600);assert.equal(precisionRow.alexUnits,3001200);assert.equal(precisionRow.pedreiroUnits,2003400);
const precisionMeasurement=await create('measurements',{requestId:crypto.randomUUID(),stageId:precisionStage.id,percent:0.001,previousId:'',periodStart:'2026-09-01',date:'2026-09-01',notes:'Percentual com quatro casas',allocations:[{name:'MA3',amountUnits:100},{name:'ALEX',amountUnits:0},{name:'Pedreiro',amountUnits:0}]});const precisionStored=sql.prepare('SELECT * FROM measurements WHERE id=?').get(precisionMeasurement.id);assert.equal(precisionStored.endP4,10);assert.equal(precisionStored.amountUnits,100);
await create('stages',{projectId:project.id,stageTypeId:'inexistente',name:'Inválida',contractValue:800,contractor:'A',start:'2026-09-01',end:'2026-09-30'},400);
await create('stages',{projectId:project.id,stageTypeId:customType.id,name:'Casas inválidas',contractValue:1.001,contractor:'A',start:'2026-09-01',end:'2026-09-30'},400);
await create('stages',{projectId:project.id,stageTypeId:customType.id,name:'Bases acima do total',contractValue:100,alexValue:60,pedreiroValue:50,contractor:'A',start:'2026-09-01',end:'2026-09-30'},400);
await request('PATCH',{kind:'stageTypes',id:'default-type-0',data:{name:'FUNDAÇÃO ESPECIAL',description:'Fundação adaptada'}});
await request('POST',{action:'initialize'});
data=await request('GET');assert.equal(data.stageTypes.length,10);assert.equal(data.stageTypes.find(t=>t.id==='default-type-0').name,'FUNDAÇÃO ESPECIAL');assert.equal(data.stages.find(s=>s.id===customStage.id).stageTypeId,customType.id);assert.equal(data.measurements.find(m=>m.id===first.id).amountCents,30000);assert.equal(data.stages.filter(s=>s.name==='FUNDAÇÃO').length,1);
console.log('PASS: catálogo persistente, nove tipos iniciais, edição, unicidade por nome, vínculo com etapas, inicialização sem sobrescrita e preservação financeira.');
console.log('PASS: nove etapas, inicialização idempotente, percentuais, períodos, cálculo em centavos, repetição segura, proteção do contrato, pagamentos, histórico, concorrência por revisão, cancelamento, conclusão em 100%, semana e compatibilidade com medições antigas.');

const split=(a,b,c)=>[{name:'MA3',amountUnits:a},{name:'ALEX',amountUnits:b},{name:'Pedreiro',amountUnits:c}];
const allocationInput={requestId:crypto.randomUUID(),stageId:customStage.id,percent:100,previousId:'',periodStart:'2026-10-01',date:'2026-10-07',notes:'Divisão'};
for(const allocations of [null,[],split(4000000,2000000,1999999),split(4000000,2000000,2000001),split(-1,4000001,4000000),split(4000000.5,2000000,1999999.5),[{name:'MA3',amountUnits:4000000},{name:'MA3',amountUnits:2000000},{name:'Pedreiro',amountUnits:2000000}]])await create('measurements',{...allocationInput,allocations},400);
assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM measurements WHERE stageId=?').get(customStage.id).n,0);
const allocated=await create('measurements',{...allocationInput,allocations:split(4000000,2400000,1600000)});
let stored=sql.prepare('SELECT * FROM measurements WHERE id=?').get(allocated.id);
assert.deepEqual(JSON.parse(stored.allocations).map(r=>r.percentP4),[500000,300000,200000]);
await create('measurements',{...allocationInput,allocations:split(4000000,2400000,1600000)},200);
await create('measurements',{...allocationInput,allocations:split(3000000,3000000,2000000)},409);
await request('PATCH',{kind:'measurements',id:allocated.id,revision:0,data:{...allocationInput,allocations:split(3000000,3000000,2000000)}});
stored=sql.prepare('SELECT * FROM measurements WHERE id=?').get(allocated.id);
assert.deepEqual(JSON.parse(stored.allocations).map(r=>r.amountUnits),[3000000,3000000,2000000]);
assert.deepEqual(JSON.parse(JSON.parse(stored.editHistory)[0].previous.allocations).map(r=>r.amountUnits),[4000000,2400000,1600000]);
await request('PATCH',{kind:'measurements',id:allocated.id,revision:0,data:{...allocationInput,allocations:split(3000000,3000000,2000000)}},409);
await request('PATCH',{action:'payment',id:allocated.id,paid:true,paidAt:'2026-10-08',revision:1});
await request('PATCH',{kind:'measurements',id:allocated.id,revision:2,data:{...allocationInput,allocations:split(0,0,8000000)}},400);
assert.equal(sql.prepare('SELECT allocations FROM measurements WHERE id=?').get(allocated.id).allocations,stored.allocations);
// A legacy measurement has no invented allocation and remains payable.
sql.prepare('UPDATE measurements SET allocations=NULL WHERE id=?').run(first.id);
await request('PATCH',{action:'payment',id:first.id,paid:true,paidAt:'2026-10-08',revision:0});
assert.equal(sql.prepare('SELECT allocations FROM measurements WHERE id=?').get(first.id).allocations,null);
console.log('PASS: allocation totals, invalid/duplicate layers, two-decimal values, four-decimal percentages, persistence, idempotency, edit audit, concurrency, paid protection and legacy preservation.');
sql.close();
