import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
function statement(query,args=[]){return {bind(...v){return statement(query,v)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}}}
globalThis.testDb={prepare:statement,async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.all());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.testEnv={OWNER_SETUP_TOKEN:'test-secret-bootstrap',OWNER_SETUP_EMAIL:'owner@example.com'};
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const env=url('export const env=globalThis.testEnv;');
const access=url(compile('db/access.ts').replace("'cloudflare:workers'",JSON.stringify(url('export const env={DB:globalThis.testDb};'))));
const permissions=url(compile('lib/permissions.ts'));
const users=url(compile('db/users.ts').replace("'./access'",JSON.stringify(access)).replace("'@/lib/permissions'",JSON.stringify(permissions)));
function route(path){return import(url(compile(path).replace("'cloudflare:workers'",JSON.stringify(env)).replace("'zod'",JSON.stringify(import.meta.resolve('zod'))).replace("'@/db/access'",JSON.stringify(access)).replace("'@/db/users'",JSON.stringify(users)).replace("'@/lib/permissions'",JSON.stringify(permissions)).replace("'@/lib/measurement'",JSON.stringify(url(compile('lib/measurement.ts'))))))}
const api=await route('app/api/users/route.ts'),data=await route('app/api/data/route.ts'),docs=await route('app/api/documents/route.ts');
const accounts={owner:['owner-stable-id','owner@example.com'],stranger:['unknown-id','unknown@example.com'],reader:['reader-stable-id','reader@example.com'],other:['other-id','other@example.com']};
async function req(target,method,who,body,status=200,extra={}){const headers={'Content-Type':'application/json',...extra};if(who){headers['oai-authenticated-user-id']=accounts[who][0];headers['oai-authenticated-user-email']=accounts[who][1]}const r=await target[method](new Request('http://localhost/api/'+(target===api?'users':'data'),{method,headers,...(body?{body:JSON.stringify(body)}:{})}));const text=await r.text();assert.equal(r.status,status,text);try{return JSON.parse(text)}catch{return text}}
await req(api,'GET',null,null,401);await req(data,'GET','stranger',null,403);
await req(api,'POST','stranger',{action:'bootstrap',token:'test-secret-bootstrap'},403);
await req(api,'POST','owner',{action:'bootstrap',token:'wrong'},403);
await req(api,'POST','owner',{action:'bootstrap',token:'test-secret-bootstrap'});
await req(api,'POST','owner',{action:'bootstrap',token:'test-secret-bootstrap'},409);
await req(api,'POST','owner',{action:'renew',id:'owner'},403,{Origin:'https://attacker.example'});
const {presets,expandPermissions}=await import(permissions);
const person={name:'Leitor',email:'reader@example.com',role:'custom',active:true,permissions:['stageTypes.view']};
await req(api,'POST','stranger',{data:{...person,role:'admin'}},403);
const created=await req(api,'POST','owner',{data:person},201);assert.ok(created.activationToken);
const list=await req(api,'GET','owner');assert.equal(list.users.length,2);assert.ok(!JSON.stringify(list).includes('activationHash'));assert.ok(!JSON.stringify(list).includes(created.activationToken));
await req(api,'POST','reader',{action:'activate',token:'invalid'},403);
await req(api,'POST','reader',{action:'activate',token:created.activationToken});
await req(api,'POST','other',{action:'activate',token:created.activationToken},403);
assert.equal((await req(api,'GET','reader')).users.length,0);
await req(data,'POST','owner',{action:'initialize'});const filtered=await req(data,'GET','reader');assert.equal(filtered.stageTypes.length,9);assert.deepEqual(filtered.projects,[]);assert.deepEqual(filtered.measurements,[]);
await req(data,'POST','reader',{kind:'stageTypes',data:{name:'Ataque',description:''}},403);
await req(data,'PATCH','reader',{action:'payment'},403);await req(data,'DELETE','reader',{id:'any'},403);
for(const method of ['GET','POST','DELETE'])await req(docs,method,'reader',method==='GET'?null:{},403);
await req(api,'PATCH','reader',{id:created.id,data:{...person,role:'admin'},revision:1},403);
let reader=(await req(api,'GET','owner')).users.find(u=>u.id===created.id);
await req(api,'PATCH','owner',{id:reader.id,revision:reader.revision,data:{...person,active:false}});
await req(data,'GET','reader',null,403);await req(api,'POST','reader',{action:'activate',token:created.activationToken},409);
let owner=(await req(api,'GET','owner')).user;
await req(api,'PATCH','owner',{id:'owner',revision:owner.revision,data:{...owner,active:false}},400);
await req(api,'PATCH','owner',{id:'owner',revision:owner.revision,data:{...owner,role:'viewer',permissions:presets.viewer}},400);
reader=(await req(api,'GET','owner')).users.find(u=>u.id===created.id);
await req(api,'PATCH','owner',{id:reader.id,revision:reader.revision,data:{...person,active:true,permissions:['stageTypes.edit']}});
await req(data,'POST','reader',{kind:'stageTypes',data:{name:'Tipo permitido',description:''}},201);
await req(api,'PATCH','owner',{id:reader.id,revision:reader.revision,data:person},409);
assert.ok(sql.prepare('SELECT COUNT(*) count FROM userAudit').get().count>=3);
assert.ok(expandPermissions(['payments.edit']).includes('projects.view'));
const pending=await req(api,'POST','owner',{data:{...person,email:'pending@example.com'}},201);
sql.prepare('UPDATE appUsers SET activationExpiresAt=? WHERE id=?').run('2000-01-01',pending.id);
await req(api,'POST','other',{action:'activate',token:pending.activationToken},403);
const renewed=await req(api,'POST','owner',{action:'renew',id:pending.id});await req(api,'POST','other',{action:'activate',token:pending.activationToken},403);await req(api,'POST','other',{action:'activate',token:renewed.activationToken});
console.log('PASS: autenticação, configuração restrita do administrador, ativação única e expiração, sigilo do token, bloqueio por módulo, pagamentos/documentos protegidos, desativação imediata, proteção do administrador, revisão concorrente e auditoria.');sql.close();
