"use client";
import {useState} from 'react';
import {KeyRound,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export async function authRequest(body:any,url='/api/auth'){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível concluir. Tente novamente.');return d}
export function LoginScreen({session,refresh,loading,loadError}:any){
 const setup=session?.setup,[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:any){e.preventDefault();setError('');if(setup&&password!==confirm){setError('As senhas não conferem.');return}setBusy(true);try{await authRequest({action:setup?'setup-owner':'login',username:username||setup?.username,password});setPassword('');setConfirm('');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="login-layout"><aside className="login-art"><div><span>MACCHIO / GESTÃO DE OBRAS</span><h1>Controle em<br/>cada etapa.</h1><p>Do projeto à entrega, suas obras conectadas.</p></div></aside><section className="login-side"><div className="login-card"><img src="/brand/macchio-logo.png" alt="Macchio Engenharia" width={260}/><div className="login-title"><KeyRound size={23}/><h2>{setup?'Defina sua primeira senha':'Acesse seu sistema'}</h2><p>{setup?'Sua conta de administrador já está vinculada. Crie uma senha para entrar diretamente no sistema.':'Entre com o usuário e a senha cadastrados pelo administrador.'}</p></div>{loading?<p role="status">Preparando acesso…</p>:loadError?<div role="alert" className="error-banner">{loadError}<button className="secondary" onClick={()=>refresh()}>Tentar novamente</button></div>:<form onSubmit={submit}><label>Usuário<input required maxLength={254} autoComplete="username" value={username||setup?.username||''} onChange={e=>setUsername(e.target.value)} placeholder="Seu usuário ou e-mail cadastrado" autoCapitalize="none" spellCheck={false}/></label><label>{setup?'Nova senha':'Senha'}<input required type="password" minLength={setup?12:undefined} maxLength={128} autoComplete={setup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{setup&&<><p className="form-hint">Use de 12 a 128 caracteres.</p><label>Confirme sua senha<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>}{error&&<div className="error-banner" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Aguarde…':setup?'Criar senha e entrar':'Entrar'}<ArrowRight size={17}/></button>{!setup&&<p className="login-help">Esqueceu sua senha? Solicite a redefinição ao administrador.</p>}{!setup&&session?.needsOwnerSetup&&<a className="login-help" href="/signin-with-chatgpt?return_to=%2F" target="_top">Configuração inicial do administrador</a>}</form>}<div className="login-footer">Seu cadastro não expira. O acesso permanece disponível enquanto estiver ativo.</div></div></section></main>
}
export function PasswordDialog({target,onClose,refresh}:any){const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[currentPassword,setCurrentPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function save(e:any){e.preventDefault();setError('');if(password!==confirm){setError('As senhas não conferem.');return}setBusy(true);try{await authRequest(target?.self?{action:'change-password',currentPassword,password}:{action:'password',id:target.id,password},target?.self?'/api/auth':'/api/users');setPassword('');setConfirm('');setCurrentPassword('');await refresh();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <Dialog open={!!target} onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{target?.self?'Minha senha':'Redefinir senha'}</DialogTitle><DialogDescription>{target?.self?'Altere sua senha de acesso.':'Defina uma nova senha para '+target?.name+'.'} As outras sessões serão encerradas.</DialogDescription></DialogHeader><form onSubmit={save}>{target?.self&&<label>Senha atual<input required type="password" maxLength={128} autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label>}<label>Nova senha<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="form-hint">Use de 12 a 128 caracteres.</p><label>Confirme a nova senha<input required type="password" minLength={12} maxLength={128} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{error&&<div role="alert" className="error-banner">{error}</div>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar senha'}</button></div></form></DialogContent></Dialog>}
