"use client";
import {useState} from 'react';
import {Plus,Pencil,Ruler} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Blank,Choice} from './obras-ui';
import {money,number,dateLabel,today,type Row} from '@/lib/obras';
import {contractCents,amountCents,stageLedger,weekRange} from '@/lib/measurement';
function Heads({items}:any){return <TableHeader><TableRow>{items.map((x:string)=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader>}
export function StagesPanel({data,projectId,start,rows:provided}:any){const rows=provided||data.stages.filter((s:Row)=>!projectId||s.projectId===projectId);return <section className="panel"><div className="section-heading"><div><h2>Etapas da obra</h2><p>Defina a empreiteira e o valor de 100% de cada etapa.</p></div><button className="primary" onClick={()=>start('stages')}><Plus size={17}/>Nova etapa</button></div>{!rows.length?<Blank title="Nenhuma etapa encontrada" description="Cadastre uma obra para receber as nove etapas iniciais ou ajuste os filtros." icon={Ruler}/>:<Table><Heads items={['Etapa / obra','Empreiteira','Valor contratado','Acumulado','Saldo a medir','']}/><TableBody>{rows.map((s:Row)=>{const ledger=stageLedger(data.measurements,s.id),pct=(ledger.at(-1)?.endBp||0)/100,base=contractCents(s);return <TableRow key={s.id}><TableCell><strong>{s.name}</strong><small className="cell-subtitle">{data.projects.find((p:Row)=>p.id===s.projectId)?.name}</small><small className="cell-subtitle">{dateLabel(s.start)} → {dateLabel(s.end)}</small></TableCell><TableCell>{s.contractor||<span className="late">A definir</span>}</TableCell><TableCell>{base?money(base/100):<span className="late">Informar valor</span>}</TableCell><TableCell><strong>{number(pct)}%</strong><Progress value={pct} className="progress-line"/></TableCell><TableCell>{money((base-ledger.reduce((t,m)=>t+amountCents(m),0))/100)}<small className="cell-subtitle">{number(100-pct)}% restante</small></TableCell><TableCell><button className="icon-button" title={'Editar '+s.name} onClick={()=>start('stages',s)}><Pencil size={17}/></button></TableCell></TableRow>})}</TableBody></Table>}</section>}
export function MeasurementsPanel({data,rows,start,demo,setRemove,scopeProjectId}:any){
 const week=weekRange(today()),[from,setFrom]=useState(week.start),[to,setTo]=useState(week.end),[status,setStatus]=useState('all');
 const inPeriod=(m:Row)=>!m.cancelledAt&&(!from||m.date>=from)&&(!to||m.date<=to);
 const period=rows.filter(inPeriod),total=period.reduce((t:number,m:Row)=>t+amountCents(m),0),paid=period.filter((m:Row)=>m.paid).reduce((t:number,m:Row)=>t+amountCents(m),0);
 const relevant=data.stages.filter((s:Row)=>!scopeProjectId||s.projectId===scopeProjectId),base=relevant.reduce((t:number,s:Row)=>t+contractCents(s),0);
 const weekly=data.measurements.filter((m:Row)=>!m.cancelledAt&&(!scopeProjectId||m.projectId===scopeProjectId)&&m.date>=week.start&&m.date<=week.end);
 const progress=(list:Row[])=>base?list.reduce((t,m)=>t+m.contractCents*(m.endBp-m.startBp)/10000,0)/base*100:0;
 const visible=rows.filter((m:Row)=>(!from||m.date>=from)&&(!to||m.date<=to)&&(status==='all'||(status==='cancelled'?m.cancelledAt:!m.cancelledAt&&(status==='paid'?m.paid:!m.paid))));
 const summaries=relevant.map((s:Row)=>{const list=period.filter((m:Row)=>m.stageId===s.id);return {s,list,value:list.reduce((t:number,m:Row)=>t+amountCents(m),0),delta:list.reduce((t:number,m:Row)=>t+m.endBp-m.startBp,0)}}).filter((r:any)=>r.list.length);
 return <><section className="panel period-panel"><div className="section-heading"><div><h2>Medições por período</h2><p>O período considera a data final de cada lançamento.</p></div><button className="primary" onClick={()=>start('measurements')}><Plus size={17}/>Nova medição</button></div><div className="period-controls"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary" onClick={()=>{setFrom(week.start);setTo(week.end)}}>Esta semana</button><button className="secondary" onClick={()=>{setFrom('');setTo('')}}>Todo o histórico</button></div>{from&&to&&from>to&&<div className="error-banner">A data final deve ser igual ou posterior à inicial.</div>}<div className="measurement-stats"><article><span>Avanço nesta semana</span><strong>{number(progress(weekly))}%</strong><small>{dateLabel(week.start)} a {dateLabel(week.end)} · ponderado por valor</small></article><article><span>Medido no período</span><strong>{money(total/100)}</strong><small>Avanço: {number(progress(period))}% ponderado</small></article><article><span>Pago no período</span><strong>{money(paid/100)}</strong><small>Medições marcadas como pagas</small></article><article><span>A pagar no período</span><strong>{money((total-paid)/100)}</strong><small>Saldo das medições pendentes</small></article></div>{summaries.length>0&&<Table><Heads items={['Etapa','Variação no período','Valor gerado']}/><TableBody>{summaries.map(({s,delta,value}:any)=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell>{number(delta/100)} p.p.</TableCell><TableCell><strong>{money(value/100)}</strong></TableCell></TableRow>)}</TableBody></Table>}</section>
 <section className="panel"><div className="section-heading"><div><h2>Histórico dos lançamentos</h2><p>Percentuais, base de cálculo e valores preservados em cada medição.</p></div><Choice label="Situação do pagamento" value={status} onChange={setStatus} options={[["all","Todas as situações"],["pending","Pendentes"],["paid","Pagas"],["cancelled","Canceladas"]]}/></div>{!visible.length?<Blank title="Nenhuma medição neste período" description="Ajuste as datas ou registre o percentual acumulado de uma etapa." icon={Ruler}/>:<Table><Heads items={['Período / etapa','Acumulado','Variação','Valor da medição','Pagamento','Ações']}/><TableBody>{visible.map((m:Row)=>{const last=stageLedger(data.measurements,m.stageId).at(-1);return <TableRow key={m.id} className={m.cancelledAt?'cancelled-row':''}><TableCell><strong>{m.stageName}</strong><small className="cell-subtitle">{data.projects.find((p:Row)=>p.id===m.projectId)?.name}</small><small className="cell-subtitle">{dateLabel(m.periodStart)} → {dateLabel(m.date)}</small><small className="cell-subtitle">{m.contractor}</small></TableCell><TableCell>{number(m.startBp/100)}% → <strong>{number(m.endBp/100)}%</strong></TableCell><TableCell>{number((m.endBp-m.startBp)/100)} p.p.</TableCell><TableCell><strong>{money(amountCents(m)/100)}</strong><small className="cell-subtitle">Base: {money(m.contractCents/100)}</small><details className="calculation-details"><summary>Ver cálculo</summary><p>{number((m.endBp-m.startBp)/100)}% de {money(m.contractCents/100)}. Arredondamento pelo total acumulado.</p>{m.notes&&<p>{m.notes}</p>}{JSON.parse(m.paymentHistory||'[]').map((h:Row,i:number)=><p key={i}>{dateLabel(h.changedAt)}: {h.paid?'Pago em '+dateLabel(h.paidAt):'Marcado como pendente'}</p>)}</details></TableCell><TableCell><span className={'status '+(m.cancelledAt?'gray':m.paid?'green':'orange')}>{m.cancelledAt?'Cancelada':m.paid?'Paga':'Pendente'}</span>{m.paidAt&&<small className="cell-subtitle">{dateLabel(m.paidAt)}</small>}</TableCell><TableCell>{!demo&&!m.cancelledAt&&<div className="ledger-actions"><button className="secondary" onClick={()=>start('payment',m)}>{m.paid?'Alterar pagamento':'Marcar como paga'}</button>{!m.paid&&last?.id===m.id&&<button className="text-button danger" onClick={()=>setRemove({kind:'measurements',row:m})}>Cancelar medição</button>}</div>}</TableCell></TableRow>})}</TableBody></Table>}</section></>;
}
