"use client";
import {Building2,LayoutDashboard,Ruler,FolderOpen,HardHat,Users,TrendingUp} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarHeader,SidebarFooter,useSidebar} from '@/components/ui/sidebar';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {money,type Row} from '@/lib/obras';
export const nav=[['overview','Visão geral',LayoutDashboard],['projects','Obras',Building2],['measurements','Medições',Ruler],['documents','Documentos',FolderOpen],['engineers','Engenheiros',HardHat],['teams','Equipes',Users]] as const;
export function Choice({value,onChange,options,label}:any){return <Select value={value||'_none'} onValueChange={v=>onChange(v==='_none'?'':v)}><SelectTrigger className="choice" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map((o:any)=>typeof o==='string'?<SelectItem key={o} value={o}>{o}</SelectItem>:<SelectItem key={o[0]} value={o[0]||'_none'}>{o[1]}</SelectItem>)}</SelectContent></Select>}
export function Status({value}:any){const colors:Record<string,string>={'Em andamento':'green',Planejamento:'blue',Pausada:'orange',Concluída:'gray'};return <span className={'status '+(colors[value]||'gray')}>{value}</span>}
export function Blank({title,description,icon:Icon=FolderOpen,action}:any){return <Empty className="empty-state"><EmptyHeader><EmptyMedia><Icon size={34}/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{action}</Empty>}
export function AppNav({view,go}:any){const {setOpenMobile}=useSidebar();return <Sidebar className="navigation"><SidebarHeader><div className="brand"><span className="brand-icon"><Building2/></span><div>MACCHIO<small>ENGENHARIA</small></div></div></SidebarHeader><SidebarContent><div className="nav-label">GESTÃO DE OBRAS</div>{nav.map(([key,label,Icon])=><button key={key} className={'nav-item '+(view===key?'active':'')} onClick={()=>{go(key);setOpenMobile(false)}}><Icon size={19}/>{label}</button>)}</SidebarContent><SidebarFooter><div className="sidebar-note"><span>PLANEJAR. EXECUTAR. MEDIR.</span><p>O controle que acompanha<br/>o ritmo da sua obra.</p></div><div className="profile"><span className="avatar">ME</span><div>Macchio Engenharia<small>Área de trabalho</small></div></div></SidebarFooter></Sidebar>}
export function Graph({data,projectId}:any){const list=data.measurements.filter((m:Row)=>!projectId||m.projectId===projectId);if(!list.length)return <Blank title="A execução ganha forma aqui" description="Registre medições para visualizar o histórico mensal." icon={TrendingUp}/>;const months=[...new Set(list.map((m:Row)=>m.date.slice(0,7)))].sort() as string[];let acc=0;const points=months.map(m=>{acc+=list.filter((r:Row)=>r.date.startsWith(m)).reduce((t:number,r:Row)=>t+r.quantity*r.unitPrice,0);return {month:m,value:acc}});const max=points.at(-1)?.value||1;const pos=points.map((p,i)=>[30+i*580/Math.max(1,points.length-1),180-150*p.value/max]);const line=pos.map(p=>p.join(',')).join(' ');return <div className="chart"><div className="chart-legend"><span><i/>Valor medido acumulado</span><strong>{money(max)}</strong></div><svg role="img" aria-label={'Evolução do valor medido: '+points.map(p=>p.month+' '+money(p.value)).join(', ')} viewBox="0 0 640 210"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d16c40" stopOpacity=".16"/><stop offset="100%" stopColor="#d16c40" stopOpacity="0"/></linearGradient></defs>{[30,80,130,180].map(y=><line key={y} x1="20" x2="620" y1={y} y2={y} stroke="#e7ebf0" strokeDasharray="4 5"/>)}<polygon points={`${pos[0][0]},190 ${line} ${pos.at(-1)![0]},190`} fill="url(#chart-fill)"/><polyline points={line} fill="none" stroke="#ce6b42" strokeWidth="3"/>{pos.map(([x,y],i)=><circle key={i} cx={x} cy={y} r="4" fill="#fff" stroke="#ce6b42" strokeWidth="2"><title>{money(points[i].value)}</title></circle>)}</svg><div className="chart-axis">{points.map((p,i)=><span key={p.month}>{points.length<9||i%Math.ceil(points.length/7)===0?new Date(p.month+'-02T12:00:00').toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}):''}</span>)}</div></div>}
