"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {Building2,Ruler,FolderOpen,Users,Plus,ArrowUpRight,ChevronRight,Search,CalendarDays,ArrowLeft,Pencil,Upload,Clock,TrendingUp,Wallet,BriefcaseBusiness,Printer} from 'lucide-react';
import {SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {empty,demo as examples,money,number,dateLabel,today,stats,countMembers,type Store,type Row} from '@/lib/obras';
import {AppNav,Choice,Blank,Graph,Status,nav,PortfolioMosaic} from './obras-ui';
import {ProjectRows,DocumentsPanel,TeamsPanel,EngineersPanel} from './panels';
import {MeasurementsPanel,StagesPanel} from './measurement-panels';
import {contractCents} from '@/lib/measurement';
import {StageTypesPanel} from './stage-types-panel';
import RecordForm from './record-form';
export default function Home(){
const [real,setReal]=useState<Store>(empty),[demo,setDemo]=useState(false),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
const [view,setView]=useState('overview'),[projectId,setProjectId]=useState(''),[detailTab,setDetailTab]=useState('overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[category,setCategory]=useState('all');
const [modal,setModal]=useState<{kind:string;row?:Row}|null>(null),[form,setForm]=useState<Row>({}),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false),[files,setFiles]=useState<File[]>([]),[remove,setRemove]=useState<{kind:string;row:Row}|null>(null);
const data=demo?examples:real;const project=data.projects.find(p=>p.id===projectId);const totals=stats(data,project?.id);const engineer=(id:string)=>data.engineers.find(e=>e.id===id)?.name||'A definir';const projectName=(id:string)=>data.projects.find(p=>p.id===id)?.name||'Sem obra vinculada';
async function refresh(initial=false){try{const init=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'initialize'})});if(init.status===401)throw new Error('Entre na sua conta para acessar os cadastros.');if(!init.ok)throw new Error('Não foi possível preparar as etapas. Recarregue para tentar novamente.');const r=await fetch('/api/data');if(r.status===401)throw new Error('Entre na sua conta para acessar os cadastros.');if(!r.ok)throw new Error('Não foi possível carregar os cadastros. Tente novamente.');const d=await r.json() as Store;setReal(d);setLoadError('');if(initial&&!d.projects.length&&!d.engineers.length&&!d.teams.length)setDemo(true);}catch(e){setLoadError((e as Error).message);}finally{setLoading(false)}}
useEffect(()=>{refresh(true)},[]);
function go(next:string){if(next==='stageTypes')setDemo(false);setView(next);setProjectId('');setQuery('');setFilter('all');setCategory('all')}
function openProject(id:string){setView('projects');setProjectId(id);setDetailTab('overview');setQuery('')}
function start(kind:string,row?:Row){if(demo&&row){toast.info('Este cadastro é demonstrativo. Use seus dados para fazer alterações.');return}const pid=!demo?projectId:'';if(demo){setDemo(false);setProjectId('');setFilter('all')}setFormError('');setFiles([]);setForm(row?{...row,contractValue:kind==='stages'?contractCents(row)/100:undefined,paid:kind==='payment'?true:!!row.paid,paidAt:row.paidAt||today()}:{name:'',description:'',stageTypeId:'',client:'',address:'',engineerId:'',start:today(),end:today(),budget:0,status:'Planejamento',notes:'',crea:'',specialty:'Engenharia Civil',email:'',phone:'',leader:'',trade:'',members:'',projectId:pid||(!demo&&filter!=='all'&&['documents','measurements','stages'].includes(view)?filter:''),contractValue:'',contractor:'',requestId:crypto.randomUUID(),percent:'',previousId:'',periodStart:today(),stageId:'',date:today(),category:'Projeto'});setModal({kind,row})}
function startScoped(kind:string,row?:Row){if(demo&&project){toast.info('Cadastre uma obra própria para registrar etapas, medições e arquivos.');return}start(kind,row)}
const update=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));
async function request(url:string,options:any){const r=await fetch(url,options);let result:any;try{result=await r.json()}catch{throw new Error('O serviço não respondeu. Tente novamente.')}if(!r.ok)throw new Error(result.error||'Não foi possível salvar. Tente novamente.');return result}
async function submit(e:FormEvent){e.preventDefault();if(!modal)return;setBusy(true);setFormError('');try{if(modal.kind==='documents'){if(!form.projectId)throw new Error('Selecione a obra.');if(!files.length)throw new Error('Selecione pelo menos um arquivo.');for(let i=0;i<files.length;i++){const fd=new FormData();fd.set('file',files[i]);fd.set('projectId',form.projectId);fd.set('category',form.category);try{await request('/api/documents',{method:'POST',body:fd});setFiles(files.slice(i+1));}catch(e){await refresh();throw new Error(`${files[i].name}: ${(e as Error).message}`)}}toast.success('Documentos importados.');}
else {const d={...form};['quantity','budget','price','contractValue','percent'].forEach(k=>{if(k in d)d[k]=Number(d[k])});['engineerId','projectId'].forEach(k=>{if(d[k]==='')d[k]=null});if(modal.kind==='measurements'&&!d.stageId)throw new Error('Selecione uma etapa.');const result=await request('/api/data',{method:modal.row?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(modal.kind==='payment'?{action:'payment',id:modal.row?.id,paid:d.paid,paidAt:d.paid?d.paidAt:null,revision:modal.row?.revision||0}:{kind:modal.kind,id:modal.row?.id,data:d})});toast.success('Cadastro salvo.');if(modal.kind==='projects')openProject(result.id)}setModal(null);await refresh();}catch(e){setFormError((e as Error).message);}finally{setBusy(false)}}
async function deleteRecord(){if(!remove)return;setBusy(true);try{await request(remove.kind==='documents'?'/api/documents':'/api/data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:remove.row.id})});setRemove(null);toast.success(remove.kind==='documents'?'Documento excluído.':'Medição cancelada.');await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'list_construction_projects',description:'Listar obras e indicadores visíveis. A resposta informa se os dados são demonstrativos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:any){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Use um objeto vazio.');return {demo,projects:data.projects.map(p=>({id:p.id,name:p.name,status:p.status,...stats(data,p.id)}))}}},{signal:lifecycle.signal})).catch(()=>{});Promise.resolve(context.registerTool({name:'open_construction_project',description:'Abrir a ficha de uma obra existente, sem alterar seus dados.',inputSchema:{type:'object',properties:{projectId:{type:'string'}},required:['projectId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:any){if(!input||typeof input.projectId!=='string'||Object.keys(input).some(k=>k!=='projectId')||!data.projects.some(p=>p.id===input.projectId))throw new Error('Obra não encontrada.');openProject(input.projectId);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {opened:input.projectId,demo}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[data,demo]);
const title=project?.name||nav.find(n=>n[0]===view)?.[1]||'Visão geral';
const filteredProjects=data.projects.filter(p=>(filter==='all'||p.status===filter)&&(p.name+' '+p.client+' '+p.address).toLowerCase().includes(query.toLowerCase()));
const matches=(r:Row)=>!query||Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase());
const scoped=(r:Row)=>(!project||r.projectId===project.id)&&(filter==='all'||!!project||r.projectId===filter);
const measurementRows=data.measurements.filter(scoped).filter(r=>matches({...r,stage:data.stages.find(s=>s.id===r.stageId)?.name,project:projectName(r.projectId)})).sort((a,b)=>b.date.localeCompare(a.date));
const documentRows=data.documents.filter(scoped).filter(d=>(category==='all'||d.category===category)&&matches(d));
const common={data,start:startScoped,demo,setRemove,scopeProjectId:projectId||(filter!=='all'?filter:'')};
return <SidebarProvider><AppNav view={view} go={go}/><main className="workspace"><header className="topbar"><span><SidebarTrigger/><img className="mobile-wordmark" src="/brand/macchio-logo.png" alt="Macchio" width={138} height={38}/><span>Área de trabalho</span><ChevronRight size={14}/><span>{project?'Obras':title}</span></span><button className="workspace-label" onClick={()=>{setDemo(!demo);setProjectId('');setFilter('all');setQuery('')}}>{demo?'Sair da demonstração':'Ver demonstração'}</button></header><div className="page">
{loading&&<div className="notice" role="status">Carregando seus cadastros…</div>}{loadError&&<div className="error-banner" role="alert">{loadError}{loadError.startsWith('Entre')?<a href="/signin-with-chatgpt?return_to=%2F" target="_top">Entrar com ChatGPT</a>:<button onClick={()=>refresh()}>Tentar novamente</button>}</div>}
{demo&&<div className="demo-banner"><span><BriefcaseBusiness size={16}/><strong>Demonstração</strong> · Dados fictícios para explorar o sistema.</span><button onClick={()=>{setDemo(false);setProjectId('');setFilter('all')}}>Usar meus dados <ArrowUpRight size={15}/></button></div>}
<div className={"page-heading "+(!project&&["overview","projects"].includes(view)?"with-portfolio":"")}><div>{project?<button className="back-link" onClick={()=>go('projects')}><ArrowLeft size={15}/>Todas as obras</button>:<div className="eyebrow">{view==='overview'?'CONTROLE EM CADA ETAPA':'MACCHIO / GESTÃO DE OBRAS'}</div>}<h1>{title}</h1><p>{project?project.address:({overview:'Suas obras, do planejamento à entrega.',projects:'Acompanhe cada empreendimento de perto.',stageTypes:'Tipos de serviços para organizar as etapas das obras.',stages:'Plano de execução e valores contratados por obra.',measurements:'Avanço percentual, valores devidos e pagamentos.',documents:'O acervo técnico e financeiro das suas obras.',engineers:'Profissionais responsáveis por cada projeto.',teams:'Pessoas e frentes de trabalho conectadas.'} as any)[view]}</p></div><div className="actions">{project?<><button className="secondary" onClick={()=>window.print()}><Printer size={17}/>Relatório</button><button className="primary" onClick={()=>start('projects',project)}><Pencil size={16}/>Editar obra</button></>:<button className="primary" onClick={()=>start(view==='overview'?'projects':view)}>{view==='documents'?<Upload size={18}/>:<Plus size={18}/>}{{overview:'Nova obra',projects:'Nova obra',stageTypes:'Novo tipo de etapa',stages:'Nova etapa',measurements:'Nova medição',documents:'Importar arquivos',engineers:'Novo engenheiro',teams:'Nova equipe'}[view]}</button>}</div>{!project&&['overview','projects'].includes(view)&&<PortfolioMosaic/>}</div>
{(view==='overview'||project)&&<div className="stats">{(project?[["Orçamento da obra",money(project.budget),'Valor de referência',Wallet],['Valor medido',money(totals.measured),'Execução acumulada',Ruler],['Avanço físico',number(totals.progress)+'%','Ponderado pelo valor das etapas',TrendingUp],['Entrega prevista',dateLabel(project.end),project.status,CalendarDays]]:[['Obras em andamento',String(data.projects.filter(p=>p.status==='Em andamento').length),`${data.projects.length} obras cadastradas`,Building2],['Valor medido',money(totals.measured),'Execução acumulada',Ruler],['Avanço físico',number(totals.progress)+'%','Ponderado pelo valor das etapas',TrendingUp],['Equipes cadastradas',String(data.teams.length),`${data.teams.reduce((a,t)=>a+countMembers(t.members),0)} integrantes nas equipes`,Users]]).map(([label,value,sub,Icon]:any)=><article className="stat" key={label}><div>{label}<Icon size={19}/></div><strong>{value}</strong><small>{sub}</small></article>)}</div>}
{view==='overview'&&<><section className="panel"><div className="section-heading"><div><h2>Acompanhamento de obras <span className="count">{data.projects.length}</span></h2><p>Uma visão do que está acontecendo no canteiro.</p></div><button className="text-button" onClick={()=>go('projects')}>Ver todas as obras <ArrowUpRight size={16}/></button></div><ProjectRows data={data} list={data.projects.slice(0,5)} openProject={openProject} start={start}/></section><div className="bottom-grid"><section className="panel"><div className="section-heading"><div><h2>Evolução da execução</h2><p>Valores acumulados por mês de medição.</p></div><span className="chart-key">R$</span></div><Graph data={data}/></section><section className="panel deadlines"><div className="section-heading"><h2>No horizonte</h2><CalendarDays size={19}/></div><p className="muted-copy">Próximas entregas previstas</p>{data.projects.filter(p=>p.status!=='Concluída').sort((a,b)=>a.end.localeCompare(b.end)).slice(0,3).map(p=><button key={p.id} className="deadline-row" onClick={()=>openProject(p.id)}><span className="date-block"><strong>{p.end.slice(8)}</strong><small>{new Date(p.end+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></span><span><strong>{p.name}</strong><small className={p.end<today()?'late':''}>{p.end<today()?'Prazo vencido':dateLabel(p.end)} · {engineer(p.engineerId).split(' ').slice(0,2).join(' ')}</small></span><ChevronRight size={16}/></button>)}{!data.projects.length&&<Blank title="Nenhum prazo cadastrado" description="As datas de entrega aparecem aqui." icon={CalendarDays}/>}<div className="deadline-footer"><Clock size={14}/> Prazos definidos no cadastro das obras.</div></section></div><section className="quick-doc"><span className="building-icon"><FolderOpen size={23}/></span><div><h3>Os documentos certos, na obra certa.</h3><p>Centralize projetos, orçamentos e comprovantes.</p></div><button className="secondary" onClick={()=>go('documents')}>Abrir documentos <ArrowUpRight size={17}/></button></section></>}
{!project&&view!=='overview'&&<div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Buscar '+(view==='projects'?'obra, cliente ou endereço…':view==='engineers'?'nome, CREA ou especialidade…':view==='stageTypes'?'nome ou descrição do tipo…':view==='documents'?'nome do documento…':['measurements','stages'].includes(view)?'etapa, obra ou observação…':'equipe, líder ou integrante…')} aria-label="Buscar cadastros"/></div>{view==='projects'?<Choice label="Situação da obra" value={filter} onChange={setFilter} options={[["all","Todas as situações"],...['Planejamento','Em andamento','Pausada','Concluída'].map(x=>[x,x])]}/>:['documents','measurements','stages'].includes(view)?<Choice label="Filtrar por obra" value={filter} onChange={setFilter} options={[["all","Todas as obras"],...data.projects.map(p=>[p.id,p.name])]}/>:<span className="result-count">{data[view as keyof Store]?.filter(matches).length||0} cadastros</span>}</div>}
{view==='projects'&&!project&&<section className="panel"><ProjectRows data={data} list={filteredProjects} openProject={openProject} start={start}/></section>}
{project&&<Tabs value={detailTab} onValueChange={setDetailTab} className="project-tabs"><TabsList>{[['overview','Resumo'],['stages','Etapas e serviços'],['measurements','Medições'],['documents','Documentos'],['teams','Equipes']].map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList><TabsContent value="overview"><div className="bottom-grid"><section className="panel"><div className="section-heading"><h2>Ficha da obra</h2><Status value={project.status}/></div><dl className="project-info"><div><dt>Cliente</dt><dd>{project.client}</dd></div><div><dt>Engenheiro responsável</dt><dd>{engineer(project.engineerId)}</dd></div><div><dt>Início previsto</dt><dd>{dateLabel(project.start)}</dd></div><div><dt>Entrega prevista</dt><dd>{dateLabel(project.end)}</dd></div><div><dt>Valor das etapas</dt><dd>{money(totals.planned)}</dd></div><div><dt>Saldo a medir nas etapas</dt><dd>{money(totals.planned-totals.measured)}</dd></div></dl>{Math.abs(totals.planned-project.budget)>.01&&<div className="notice">As etapas somam {money(totals.planned)}. O orçamento de referência é {money(project.budget)}.</div>}{project.notes&&<div className="notes"><h3>Observações</h3><p>{project.notes}</p></div>}<p className="calculation-note">Avanço físico = valor executado nas etapas ÷ valor previsto das etapas. Valor medido não significa valor pago.</p></section><section className="panel"><h2>Evolução da obra</h2><Graph data={data} projectId={project.id}/></section></div><StagesPanel {...common} projectId={projectId}/></TabsContent><TabsContent value="stages"><StagesPanel {...common} projectId={projectId}/></TabsContent><TabsContent value="measurements"><MeasurementsPanel {...common} rows={measurementRows}/></TabsContent><TabsContent value="documents"><DocumentsPanel {...common} rows={documentRows} category={category} setCategory={setCategory}/></TabsContent><TabsContent value="teams"><div className="section-heading"><h2>Equipes vinculadas à obra</h2><button className="primary" onClick={()=>startScoped('teams')}><Plus size={17}/>Nova equipe</button></div><TeamsPanel {...common} list={data.teams.filter(t=>t.projectId===projectId)}/></TabsContent></Tabs>}
{view==='stageTypes'&&!project&&<StageTypesPanel data={data} rows={data.stageTypes.filter(matches).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))} start={start}/>}
{view==='stages'&&!project&&<StagesPanel {...common} rows={data.stages.filter(scoped).filter(matches)}/>}
{view==='measurements'&&!project&&<MeasurementsPanel {...common} rows={measurementRows}/>}{view==='documents'&&!project&&<DocumentsPanel {...common} rows={documentRows} category={category} setCategory={setCategory}/>}
{view==='engineers'&&<EngineersPanel {...common} list={data.engineers.filter(matches)}/>}{view==='teams'&&<TeamsPanel {...common} list={data.teams.filter(matches)}/>}
<footer className="page-footer"><span>MACCHIO <span>ENGENHARIA</span></span><span>Do projeto à entrega.</span></footer></div></main>
<RecordForm {...{modal,setModal,form,update,real,files,setFiles,busy,formError,submit}}/>
<AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{remove?.kind==='documents'?'Excluir documento':'Cancelar medição'}?</AlertDialogTitle><AlertDialogDescription>{remove?.kind==='documents'?`O arquivo “${remove.row.name}” será removido da obra. Esta ação não pode ser desfeita.`:'A medição será cancelada e deixará de compor o saldo. O lançamento e o cálculo permanecerão no histórico. Somente a última medição pendente pode ser cancelada.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();deleteRecord()}}>{busy?'Processando…':remove?.kind==='documents'?'Excluir documento':'Confirmar cancelamento'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster richColors position="bottom-right"/></SidebarProvider>
}


