"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {Building2,Ruler,FolderOpen,Users,Plus,ArrowUpRight,ChevronRight,Search,CalendarDays,ArrowLeft,Pencil,Upload,Clock,LogOut,KeyRound,TrendingUp,Wallet,Printer} from 'lucide-react';
import {SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {empty,money,number,dateLabel,today,stats,countMembers,type Store,type Row} from '@/lib/obras';
import {AppNav,Choice,Blank,Graph,Status,nav,PortfolioMosaic} from './obras-ui';
import {ProjectRows,DocumentsPanel,TeamsPanel,EngineersPanel} from './panels';
import {MeasurementsPanel,StagesPanel} from './measurement-panels';
import {contractUnits,alexContractUnits,pedreiroContractUnits,stageAllocationBases,amountUnits,payableUnits,endPercentUnits,allocationDrafts,resolveStageAllocationDrafts,resolveMeasurementInput,stageLedger,VALUE_SCALE,PERCENT_SCALE} from '@/lib/measurement';
import {StageTypesPanel} from './stage-types-panel';
import {AccessContext,AccessButton} from './access-ui';
import {UsersPanel} from './users-panel';
import {LoginScreen,PasswordDialog,authRequest} from './login-screen';
import {hasPermission} from '@/lib/permissions';
import RecordForm from './record-form';
import {RecordDetails} from './record-details';
import {MeasurementBatchForm,newBatchMeasurementItem} from './measurement-batch-form';
import {FinancePanel} from './finance-panel';
export default function Home(){
const [session,setSession]=useState<any>(null),[passwordOpen,setPasswordOpen]=useState(false);
const can=(p:string)=>hasPermission(session?.user,p);
const [real,setReal]=useState<Store>(empty),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
const [view,setView]=useState('overview'),[projectId,setProjectId]=useState(''),[detailTab,setDetailTab]=useState('overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[category,setCategory]=useState('all');
const [inspecting,setInspecting]=useState<any>(null);
function inspect(kind:string,row:Row){if(can(kind+'.view'))setInspecting({kind,row})}
const [modal,setModal]=useState<{kind:string;row?:Row}|null>(null),[form,setForm]=useState<Row>({}),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false),[files,setFiles]=useState<File[]>([]),[remove,setRemove]=useState<{kind:string;row:Row}|null>(null);
const data=real;const project=data.projects.find(p=>p.id===projectId);const totals=stats(data,project?.id);const engineer=(id:string)=>data.engineers.find(e=>e.id===id)?.name||'A definir';const projectName=(id:string)=>data.projects.find(p=>p.id===id)?.name||'Sem obra vinculada';
async function refresh(initial=false){try{const access=await fetch('/api/users');if(access.status===401)throw new Error('Entre na sua conta para acessar os cadastros.');if(!access.ok)throw new Error('Não foi possível consultar suas permissões. Tente novamente.');const account:any=await access.json();setSession(account);setLoadError('');if(!account.user?.active){setReal(empty);setInspecting(null);setModal(null);setRemove(null);return}const init=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'initialize'})});if(init.status===401)throw new Error('Entre na sua conta para acessar os cadastros.');if(!init.ok)throw new Error('Não foi possível preparar as etapas. Recarregue para tentar novamente.');const r=await fetch('/api/data');if(r.status===401)throw new Error('Entre na sua conta para acessar os cadastros.');if(!r.ok)throw new Error('Não foi possível carregar os cadastros. Tente novamente.');const d=await r.json() as Store;setReal(d);setLoadError('');}catch(e){setReal(empty);setLoadError((e as Error).message);}finally{setLoading(false)}}
useEffect(()=>{refresh(true)},[]);
function go(next:string){if(next!=='overview'&&!can(next==='users'?'users.manage':next==='finance'?'measurements.view':next+'.view')){toast.error('Acesso não permitido.');return}setView(next);setProjectId('');setQuery('');setFilter('all');setCategory('all')}
function openProject(id:string){setView('projects');setProjectId(id);setDetailTab('overview');setQuery('')}
function start(kind:string,row?:Row){const permission=kind==='payment'?'payments.edit':kind==='measurementBatch'?'measurements.edit':kind+'.edit';if(!can(permission)){toast.error('Você não tem permissão para alterar este cadastro.');return}const pid=projectId||(filter!=='all'&&['documents','measurements','stages'].includes(view)?filter:'');setFormError('');setFiles([]);if(kind==='measurementBatch'){setForm({projectId:pid,measurementItems:[newBatchMeasurementItem()]});setModal({kind});return}setForm(row?{...row,contractValue:kind==='stages'?contractUnits(row)/VALUE_SCALE:undefined,alexValue:kind==='stages'?alexContractUnits(row)/VALUE_SCALE:undefined,pedreiroValue:kind==='stages'?pedreiroContractUnits(row)/VALUE_SCALE:undefined,paid:kind==='payment'?true:!!row.paid,paidAt:row.paidAt||today()}:{name:'',description:'',stageTypeId:'',client:'',address:'',engineerId:'',start:today(),end:today(),budget:0,status:'Planejamento',notes:'',crea:'',specialty:'Engenharia Civil',email:'',phone:'',leader:'',trade:'',members:'',projectId:pid,contractValue:'',alexValue:0,pedreiroValue:0,contractor:'',requestId:crypto.randomUUID(),percent:'',measurementInput:'percent',measurementValue:'',previousId:'',periodStart:today(),stageId:'',date:today(),category:'Projeto'});if(kind==='measurements'&&row){const ledger=stageLedger(data.measurements,row.stageId),position=ledger.findIndex(m=>m.id===row.id),prior=ledger.slice(0,position);setForm(f=>({...f,percent:endPercentUnits(row)/PERCENT_SCALE,measurementInput:'amount',measurementValue:(amountUnits(row)/VALUE_SCALE).toFixed(2),requestId:row.id,previousId:prior.at(-1)?.id||'',allocationDrafts:allocationDrafts(row.allocations,amountUnits(row))}))}setModal({kind,row})}
function startScoped(kind:string,row?:Row){start(kind,row)}
const update=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));
async function request(url:string,options:any){const r=await fetch(url,options);let result:any;try{result=await r.json()}catch{throw new Error('O serviço não respondeu. Tente novamente.')}if(!r.ok)throw new Error(result.error||'Não foi possível salvar. Tente novamente.');return result}
async function submit(e:FormEvent){e.preventDefault();if(!modal)return;setBusy(true);setFormError('');try{if(modal.kind==='measurementBatch'){if(!form.projectId)throw new Error('Selecione a obra.');const rawItems:Row[]=form.measurementItems||[];if(!rawItems.length)throw new Error('Adicione pelo menos uma etapa.');if(new Set(rawItems.map(item=>item.stageId)).size!==rawItems.length)throw new Error('Cada etapa pode aparecer apenas uma vez na medição.');const items=rawItems.map(item=>{const d:Row={...item,percent:Number(item.percent)};if(d.measurementInput==='amount')d.measurementValue=Number(d.measurementValue);else delete d.measurementValue;const stage=real.stages.find(candidate=>candidate.id===d.stageId&&candidate.projectId===form.projectId),ledger=stageLedger(real.measurements,d.stageId),measurement=resolveMeasurementInput('measurements',d.measurementInput,stage?contractUnits(stage):0,d.percent,d.measurementValue,ledger.reduce((sum,row)=>sum+amountUnits(row),0));if(!stage||!measurement||measurement.endP4<=endPercentUnits(ledger.at(-1)||{}))throw new Error('Confira o valor ou percentual informado em todas as etapas.');const allocation=resolveStageAllocationDrafts(stageAllocationBases(stage),d.allocationDrafts||allocationDrafts(null,0));if(!allocation.valid)throw new Error(`Confira os valores de MA3, ALEX e Pedreiro na etapa ${stage.name}.`);d.previousId=ledger.at(-1)?.id||'';d.allocations=allocation.valid.map(({name,amountUnits})=>({name,amountUnits}));delete d.allocationDrafts;return d});const result=await request('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'measurements.batch',projectId:form.projectId,items})});toast.success(`${result.ids.length} ${result.ids.length===1?'medição salva':'medições salvas'} com sucesso.`);}
else if(modal.kind==='documents'&&modal.row){await request('/api/documents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:modal.row.id,name:form.name,projectId:form.projectId,category:form.category})});toast.success('Documento atualizado.');}
else if(modal.kind==='documents'){if(!form.projectId)throw new Error('Selecione a obra.');if(!files.length)throw new Error('Selecione pelo menos um arquivo.');for(let i=0;i<files.length;i++){const fd=new FormData();fd.set('file',files[i]);fd.set('projectId',form.projectId);fd.set('category',form.category);try{await request('/api/documents',{method:'POST',body:fd});setFiles(files.slice(i+1));}catch(e){await refresh();throw new Error(`${files[i].name}: ${(e as Error).message}`)}}toast.success('Documentos importados.');}
else {const d={...form};['quantity','budget','price','contractValue','alexValue','pedreiroValue','percent'].forEach(k=>{if(k in d)d[k]=Number(d[k])});['engineerId','projectId'].forEach(k=>{if(d[k]==='')d[k]=null});if(modal.kind==='measurements'&&!d.stageId)throw new Error('Selecione uma etapa.');if(modal.kind==='measurements'){if(d.measurementInput==='amount')d.measurementValue=Number(d.measurementValue);else delete d.measurementValue;const stage=real.stages.find(s=>s.id===d.stageId),ledger=stageLedger(real.measurements,d.stageId),rowId=modal.row?.id,position=rowId?ledger.findIndex(m=>m.id===rowId):ledger.length,prior=ledger.slice(0,position);const measurement=resolveMeasurementInput('measurements',d.measurementInput,stage?contractUnits(stage):0,d.percent,d.measurementValue,prior.reduce((sum,m)=>sum+amountUnits(m),0));if(!measurement)throw new Error('Informe um valor ou percentual válido para a medição.');const allocation=resolveStageAllocationDrafts(stageAllocationBases(stage),d.allocationDrafts||allocationDrafts(d.allocations,modal.row?amountUnits(modal.row):0));if(!allocation.valid)throw new Error('Confira os valores de MA3, ALEX e Pedreiro em relação às bases cadastradas.');d.allocations=allocation.valid.map(({name,amountUnits})=>({name,amountUnits}));delete d.allocationDrafts;}const result=await request('/api/data',{method:modal.row?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(modal.kind==='payment'?{action:'payment',id:modal.row?.id,paid:d.paid,paidAt:d.paid?d.paidAt:null,revision:modal.row?.revision||0}:{kind:modal.kind,id:modal.row?.id,revision:modal.row?.revision,data:d})});toast.success('Cadastro salvo.');if(modal.kind==='projects')openProject(result.id)}setModal(null);await refresh();}catch(e){setFormError((e as Error).message);}finally{setBusy(false)}}
async function deleteRecord(){if(!remove)return;setBusy(true);try{await request(remove.kind==='documents'?'/api/documents':'/api/data',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:remove.row.id,kind:remove.kind,revision:remove.row.revision||0})});setRemove(null);toast.success(remove.kind==='measurements'?'Medição excluída do saldo; histórico preservado.':'Cadastro excluído.');if(remove.kind==='projects'&&remove.row.id===projectId){setProjectId('');setView('projects')}await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'list_construction_projects',description:'Listar obras e indicadores visíveis. ',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:any){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Use um objeto vazio.');return {projects:data.projects.map(p=>({id:p.id,name:p.name,status:p.status,...stats(data,p.id)}))}}},{signal:lifecycle.signal})).catch(()=>{});Promise.resolve(context.registerTool({name:'open_construction_project',description:'Abrir a ficha de uma obra existente, sem alterar seus dados.',inputSchema:{type:'object',properties:{projectId:{type:'string'}},required:['projectId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:any){if(!input||typeof input.projectId!=='string'||Object.keys(input).some(k=>k!=='projectId')||!data.projects.some(p=>p.id===input.projectId))throw new Error('Obra não encontrada.');openProject(input.projectId);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {opened:input.projectId}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[data]);
const title=project?.name||nav.find(n=>n[0]===view)?.[1]||'Visão geral';
const filteredProjects=data.projects.filter(p=>(filter==='all'||p.status===filter)&&(p.name+' '+p.client+' '+p.address).toLowerCase().includes(query.toLowerCase()));
const matches=(r:Row)=>!query||Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase());
const scoped=(r:Row)=>(!project||r.projectId===project.id)&&(filter==='all'||!!project||r.projectId===filter);
const measurementRows=data.measurements.filter(scoped).filter(r=>matches({...r,stage:data.stages.find(s=>s.id===r.stageId)?.name,project:projectName(r.projectId)})).sort((a,b)=>b.date.localeCompare(a.date));
const documentRows=data.documents.filter(scoped).filter(d=>(category==='all'||d.category===category)&&matches(d));
const common={data,can,start:startScoped,inspect,setRemove,scopeProjectId:projectId||(filter!=='all'?filter:'')};
if(!session?.user?.active)return <LoginScreen {...{session,refresh,loading,loadError}}/>;
return <AccessContext.Provider value={session?.user}><SidebarProvider><AppNav view={view} go={go} can={can}/><main className="workspace"><header className="topbar"><span><SidebarTrigger/><img className="mobile-wordmark" src="/brand/macchio-logo.png" alt="Macchio" width={138} height={38}/><span>Gestão de obras</span><ChevronRight size={14}/><span>{project?'Obras':title}</span></span><div className="account-actions"><div className="account-user"><span className="account-avatar">{session.user.name.slice(0,1)}</span><span>{session.user.name}<small>{session.user.role==='admin'?'Administrador':'Equipe Macchio'}</small></span></div><button className="text-button" onClick={()=>setPasswordOpen(true)}><KeyRound size={16}/>Minha senha</button><button className="secondary" onClick={async()=>{try{await authRequest({action:'logout'});setSession(null);setReal(empty);setView('overview');setProjectId('');setModal(null);setRemove(null);await refresh()}catch(e){toast.error((e as Error).message)}}}><LogOut size={16}/>Sair</button></div></header><div className="page">
{loading&&<div className="notice" role="status">Carregando seus cadastros…</div>}{loadError&&<div className="error-banner" role="alert">{loadError}<button onClick={()=>refresh()}>Tentar novamente</button></div>}
<div className="page-heading"><div>{project?<button className="back-link" onClick={()=>go('projects')}><ArrowLeft size={15}/>Todas as obras</button>:<div className="eyebrow">{view==='overview'?'PAINEL DE ACOMPANHAMENTO':'GESTÃO DE OBRAS'}</div>}<h1>{title}</h1><p>{project?project.address:({overview:'Acompanhe a execução, os prazos e os valores de suas obras.',projects:'Acompanhe cada empreendimento de perto.',users:'Cadastros e privilégios de acesso ao sistema.',stageTypes:'Tipos de serviços para organizar as etapas das obras.',stages:'Plano de execução e valores contratados por obra.',measurements:'Avanço percentual, valores devidos e pagamentos.',finance:'Valores pagos e a pagar por período, empresa e obra.',documents:'O acervo técnico e financeiro das suas obras.',engineers:'Profissionais responsáveis por cada projeto.',teams:'Pessoas e frentes de trabalho conectadas.'} as any)[view]}</p></div><div className="actions">{project?<><button className="secondary" onClick={()=>window.print()}><Printer size={17}/>Relatório</button><AccessButton permission="projects.edit" className="primary" onClick={()=>start('projects',project)}><Pencil size={16}/>Editar obra</AccessButton></>:view==='users'||view==='finance'?null:<AccessButton permission={(view==='overview'?'projects':view)+'.edit'} className="primary" onClick={()=>start(view==='measurements'?'measurementBatch':view==='overview'?'projects':view)}>{view==='documents'?<Upload size={18}/>:<Plus size={18}/>}{{overview:'Nova obra',projects:'Nova obra',stageTypes:'Novo tipo de etapa',stages:'Nova etapa',measurements:'Nova medição',documents:'Importar arquivos',engineers:'Novo engenheiro',teams:'Nova equipe'}[view]}</AccessButton>}</div></div>
{(view==='overview'||project)&&can('measurements.view')&&<div className="stats">{(project?[["Orçamento da obra",money(project.budget),'Valor de referência',Wallet],['Valor medido MA3',money(totals.measured),'Execução acumulada',Ruler],['Avanço físico',number(totals.progress)+'%','Ponderado pelo valor das etapas',TrendingUp],['Entrega prevista',dateLabel(project.end),project.status,CalendarDays]]:[['Obras em andamento',String(data.projects.filter(p=>p.status==='Em andamento').length),`${data.projects.length} obras cadastradas`,Building2],['Valor medido MA3',money(totals.measured),'Execução acumulada',Ruler],['Avanço físico',number(totals.progress)+'%','Ponderado pelo valor das etapas',TrendingUp],['Saldo a pagar',money(data.measurements.filter(m=>!m.paid&&!m.cancelledAt).reduce((sum,m)=>sum+payableUnits(m)/VALUE_SCALE,0)),'Total financeiro das medições pendentes',Wallet]]).map(([label,value,sub,Icon]:any)=><article className="stat" key={label}><div>{label}<Icon size={19}/></div><strong>{value}</strong><small>{sub}</small></article>)}</div>}
{view==='overview'&&<div className="workspace-shortcuts">{[['projects','Obras','Cadastros e acompanhamento',Building2],['measurements','Medições e pagamentos','Histórico e valores por período',Ruler],['finance','Financeiro','Pagos e a pagar por período',Wallet],['documents','Documentos','Projetos, orçamentos e comprovantes',FolderOpen]].filter(([key])=>can(key==='finance'?'measurements.view':key+'.view')).map(([key,label,sub,Icon]:any)=><button key={key} onClick={()=>go(key)}><span className="shortcut-icon"><Icon size={21}/></span><span><strong>{label}</strong><small>{sub}</small></span><ChevronRight size={17}/></button>)}</div>}
{view==='overview'&&!can('measurements.view')&&<div className="notice">Os indicadores exibem somente os módulos liberados para seu usuário.</div>}{view==='overview'&&<><section className="panel"><div className="section-heading"><div><h2>Acompanhamento de obras <span className="count">{data.projects.length}</span></h2><p>Uma visão do que está acontecendo no canteiro.</p></div><button className="text-button" onClick={()=>go('projects')}>Ver todas as obras <ArrowUpRight size={16}/></button></div><ProjectRows data={data} list={data.projects.slice(0,5)} openProject={openProject} start={start} setRemove={setRemove}/></section><div className="bottom-grid"><section className="panel"><div className="section-heading"><div><h2>Evolução da execução</h2><p>Valores acumulados por mês de medição.</p></div><span className="chart-key">R$</span></div><Graph data={data}/></section><section className="panel deadlines"><div className="section-heading"><h2>No horizonte</h2><CalendarDays size={19}/></div><p className="muted-copy">Próximas entregas previstas</p>{data.projects.filter(p=>p.status!=='Concluída').sort((a,b)=>a.end.localeCompare(b.end)).slice(0,3).map(p=><button key={p.id} className="deadline-row" onClick={()=>openProject(p.id)}><span className="date-block"><strong>{p.end.slice(8)}</strong><small>{new Date(p.end+'T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></span><span><strong>{p.name}</strong><small className={p.end<today()?'late':''}>{p.end<today()?'Prazo vencido':dateLabel(p.end)} · {engineer(p.engineerId).split(' ').slice(0,2).join(' ')}</small></span><ChevronRight size={16}/></button>)}{!data.projects.length&&<Blank title="Nenhum prazo cadastrado" description="As datas de entrega aparecem aqui." icon={CalendarDays}/>}<div className="deadline-footer"><Clock size={14}/> Prazos definidos no cadastro das obras.</div></section></div><section className="quick-doc"><span className="building-icon"><FolderOpen size={23}/></span><div><h3>Os documentos certos, na obra certa.</h3><p>Centralize projetos, orçamentos e comprovantes.</p></div><button className="secondary" onClick={()=>go('documents')}>Abrir documentos <ArrowUpRight size={17}/></button></section></>}
{!project&&!['overview','users','finance'].includes(view)&&<div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Buscar '+(view==='projects'?'obra, cliente ou endereço…':view==='engineers'?'nome, CREA ou especialidade…':view==='stageTypes'?'nome ou descrição do tipo…':view==='documents'?'nome do documento…':['measurements','stages'].includes(view)?'etapa, obra ou observação…':'equipe, líder ou integrante…')} aria-label="Buscar cadastros"/></div>{view==='projects'?<Choice label="Situação da obra" value={filter} onChange={setFilter} options={[["all","Todas as situações"],...['Planejamento','Em andamento','Pausada','Concluída'].map(x=>[x,x])]}/>:['documents','measurements','stages'].includes(view)?<Choice label="Filtrar por obra" value={filter} onChange={setFilter} options={[["all","Todas as obras"],...data.projects.map(p=>[p.id,p.name])]}/>:<span className="result-count">{data[view as keyof Store]?.filter(matches).length||0} cadastros</span>}</div>}
{view==='projects'&&!project&&<section className="panel"><ProjectRows data={data} list={filteredProjects} openProject={openProject} start={start} setRemove={setRemove}/></section>}
{project&&<Tabs value={detailTab} onValueChange={setDetailTab} className="project-tabs"><TabsList>{[['overview','Resumo'],['stages','Etapas e serviços'],['measurements','Medições'],['documents','Documentos'],['teams','Equipes']].filter(([key])=>key==='overview'||can(key+'.view')).map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList><TabsContent value="overview"><div className="bottom-grid"><section className="panel"><div className="section-heading"><h2>Ficha da obra</h2><Status value={project.status}/></div><dl className="project-info"><div><dt>Cliente</dt><dd>{project.client}</dd></div><div><dt>Engenheiro responsável</dt><dd>{engineer(project.engineerId)}</dd></div><div><dt>Início previsto</dt><dd>{dateLabel(project.start)}</dd></div><div><dt>Entrega prevista</dt><dd>{dateLabel(project.end)}</dd></div>{can('stages.view')&&<div><dt>Valor das etapas</dt><dd>{money(totals.planned)}</dd></div>}{can('measurements.view')&&<div><dt>Saldo a medir nas etapas</dt><dd>{money(totals.planned-totals.measured)}</dd></div>}</dl>{can('stages.view')&&Math.abs(totals.planned-project.budget)>.0001&&<div className="notice">As etapas somam {money(totals.planned)}. O orçamento de referência é {money(project.budget)}.</div>}{project.notes&&<div className="notes"><h3>Observações</h3><p>{project.notes}</p></div>}<p className="calculation-note">Avanço físico = valor executado nas etapas ÷ valor previsto das etapas. Valor medido não significa valor pago.</p></section><section className="panel"><h2>Evolução da obra</h2><Graph data={data} projectId={project.id}/></section></div>{can('stages.view')&&<StagesPanel {...common} projectId={projectId}/>}</TabsContent><TabsContent value="stages"><StagesPanel {...common} projectId={projectId}/></TabsContent><TabsContent value="measurements"><MeasurementsPanel {...common} rows={measurementRows}/></TabsContent><TabsContent value="documents"><DocumentsPanel {...common} rows={documentRows} category={category} setCategory={setCategory}/></TabsContent><TabsContent value="teams"><div className="section-heading"><h2>Equipes vinculadas à obra</h2><AccessButton permission="teams.edit" className="primary" onClick={()=>startScoped('teams')}><Plus size={17}/>Nova equipe</AccessButton></div><TeamsPanel {...common} list={data.teams.filter(t=>t.projectId===projectId)}/></TabsContent></Tabs>}
{view==='users'&&can('users.manage')&&<UsersPanel session={session} refresh={refresh}/>}
{view==='stageTypes'&&!project&&<StageTypesPanel inspect={inspect} setRemove={setRemove} data={data} rows={data.stageTypes.filter(matches).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'))} start={start}/>}
{view==='stages'&&!project&&<StagesPanel {...common} rows={data.stages.filter(scoped).filter(matches)}/>}
{view==='measurements'&&!project&&<MeasurementsPanel {...common} rows={measurementRows}/>} {view==='finance'&&!project&&can('measurements.view')&&<FinancePanel data={data}/>} {view==='documents'&&!project&&<DocumentsPanel {...common} rows={documentRows} category={category} setCategory={setCategory}/>}
{view==='engineers'&&<EngineersPanel {...common} list={data.engineers.filter(matches)}/>}{view==='teams'&&<TeamsPanel {...common} list={data.teams.filter(matches)}/>}
{view==='overview'&&<div className="portfolio-section"><div><span className="eyebrow">MACCHIO ENGENHARIA</span><h2>Projetos que inspiram.</h2><p>Conheça o portfólio da empresa.</p></div><PortfolioMosaic/></div>}
<footer className="page-footer"><span>MACCHIO <span>ENGENHARIA</span></span><span>Do projeto à entrega.</span></footer></div></main>
{passwordOpen&&<PasswordDialog target={{...session.user,self:true}} onClose={()=>setPasswordOpen(false)} refresh={refresh}/>}
<RecordDetails target={inspecting} onClose={()=>setInspecting(null)} onEdit={(kind:string,row:Row)=>{setInspecting(null);start(kind,row)}} data={data}/>
{modal?.kind!=='measurementBatch'&&<RecordForm {...{modal,setModal,form,update,real,files,setFiles,busy,formError,submit}}/>}
<MeasurementBatchForm {...{modal,setModal,form,update,real,busy,formError,submit}}/>
<AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir {remove?.kind==='measurements'?'medição':remove?.kind==='projects'?'obra':remove?.kind==='stages'?'etapa':remove?.kind==='stageTypes'?'tipo de etapa':remove?.kind==='engineers'?'engenheiro':remove?.kind==='teams'?'equipe':'documento'}?</AlertDialogTitle><AlertDialogDescription>{remove?.kind==='measurements'?'A medição deixará de compor o saldo, mas o lançamento e o cálculo serão preservados no histórico. Quando houver uma medição posterior pendente, o período e os valores serão recompostos automaticamente sem ultrapassar as bases da etapa.':`O cadastro “${remove?.row.name}” será removido. Registros com vínculos precisam ser desvinculados antes. Esta ação não pode ser desfeita.`}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();deleteRecord()}}>{busy?'Processando…':'Confirmar exclusão'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster richColors position="bottom-right"/></SidebarProvider></AccessContext.Provider>
}


