"use client";
import {Upload,FileText} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Choice} from './obras-ui';
import {labels,categories,money,number} from '@/lib/obras';
export default function RecordForm({modal,setModal,form,update,real,files,setFiles,busy,formError,submit}:any){const projectOptions=[['','Selecione uma obra'],...real.projects.map((p:any)=>[p.id,p.name])];const stageOptions=real.stages.filter((s:any)=>s.projectId===form.projectId);const selectedStage=real.stages.find((s:any)=>s.id===form.stageId);const used=real.measurements.filter((m:any)=>m.stageId===form.stageId).reduce((a:number,m:any)=>a+m.quantity,0);
const field=(key:string,label:string,type='text',extra:any={})=>{const {wide,optional,...attrs}=extra;return <label className={wide?'wide':''} key={key}>{label}<input name={key} type={type} value={form[key]??''} onChange={e=>update(key,e.target.value)} required={!optional} maxLength={type==='text'?1000:undefined} {...(type==='number'?{min:0,step:'any'}:{})} {...attrs}/></label>};
const choiceField=(key:string,label:string,options:any)=><label key={key}>{label}<Choice value={form[key]} onChange={(v:string)=>{update(key,v);if(key==='projectId')update('stageId','')}} options={options} label={label}/></label>;
return <Dialog open={!!modal} onOpenChange={v=>{if(!busy&&!v)setModal(null)}}><DialogContent className="form-dialog" showCloseButton={!busy}><DialogHeader><DialogTitle>{modal?.kind==='documents'?'Importar documentos':`${modal?.row?'Editar':'Cadastrar'} ${labels[modal?.kind||'projects']}`}</DialogTitle><DialogDescription>{modal?.kind==='measurements'?'Informe somente a quantidade executada neste registro. O sistema calcula o acumulado.':modal?.kind==='documents'?'Selecione a obra e os arquivos. Limite de 25 MB por arquivo.':'Preencha os dados para manter o acompanhamento atualizado.'}</DialogDescription></DialogHeader><form onSubmit={submit}><div className="form-grid">
{modal?.kind==='projects'&&<>{field('name','Nome da obra')}{field('client','Cliente')}{field('address','Endereço / localização','text',{wide:true})}{choiceField('engineerId','Engenheiro responsável',[['','A definir'],...real.engineers.map((e:any)=>[e.id,e.name])])}{choiceField('status','Situação',['Planejamento','Em andamento','Pausada','Concluída'])}{field('start','Início previsto','date')}{field('end','Entrega prevista','date')}{field('budget','Orçamento de referência (R$)','number')}<label className="wide">Observações<textarea maxLength={1000} value={form.notes} onChange={e=>update('notes',e.target.value)}/></label>{!real.engineers.length&&<p className="form-hint wide">Você pode cadastrar o engenheiro na seção Engenheiros e vinculá-lo depois.</p>}</>}
{modal?.kind==='engineers'&&<>{field('name','Nome completo')}{field('crea','CREA / registro e UF')}{field('specialty','Especialidade')}{field('phone','Telefone','tel',{optional:true})}{field('email','E-mail','email',{optional:true})}</>}
{modal?.kind==='teams'&&<>{field('name','Nome da equipe')}{field('trade','Especialidade / serviço')}{field('leader','Líder da equipe')}{choiceField('projectId','Obra vinculada',[['','Sem obra vinculada'],...real.projects.map((p:any)=>[p.id,p.name])])}<label className="wide">Integrantes <span className="muted-copy">(um nome por linha)</span><textarea rows={5} value={form.members} onChange={e=>update('members',e.target.value)} maxLength={10000} placeholder={'Nome do integrante\nNome do integrante'}/></label></>}
{modal?.kind==='stages'&&<>{choiceField('projectId','Obra',projectOptions)}{field('name','Etapa / serviço')}{choiceField('unit','Unidade',['m²','m³','m','un','kg','h','vb'])}{field('quantity','Quantidade prevista','number',{min:0.000001})}{field('price','Preço unitário (R$)','number',{min:0.000001})}{field('start','Início previsto','date')}{field('end','Fim previsto','date')}<div className="form-total wide"><span>Valor previsto da etapa</span><strong>{money(Number(form.quantity)*Number(form.price))}</strong></div></>}
{modal?.kind==='measurements'&&<>{choiceField('projectId','Obra',projectOptions)}{choiceField('stageId','Etapa / serviço',[['','Selecione uma etapa'],...stageOptions.map((s:any)=>[s.id,s.name])])}{field('date','Data da medição','date')}{field('quantity',`Quantidade executada${selectedStage?' ('+selectedStage.unit+')':''}`,'number',{min:0.000001,max:selectedStage?Math.max(0,selectedStage.quantity-used):undefined})}{selectedStage&&<div className="notice wide">Previsto: {number(selectedStage.quantity)} {selectedStage.unit} · Já medido: {number(used)} · Saldo: {number(selectedStage.quantity-used)} {selectedStage.unit}</div>}{form.projectId&&!stageOptions.length&&<p className="form-hint wide">Esta obra ainda não tem etapas. Abra a ficha da obra e cadastre uma etapa antes de medir.</p>}<label className="wide">Observações<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} maxLength={1000}/></label><div className="form-total wide"><span>Valor desta medição</span><strong>{money((Number(form.quantity)||0)*(selectedStage?.price||0))}</strong></div></>}
{modal?.kind==='documents'&&<>{choiceField('projectId','Obra',projectOptions)}{choiceField('category','Categoria',categories)}<label className="upload-zone wide"><Upload size={30}/><strong>Selecione os arquivos da obra</strong><span>PDF, DWG, DXF, IFC, planilhas, imagens, documentos e ZIP</span><input type="file" multiple accept=".pdf,.dwg,.dxf,.ifc,.xlsx,.xls,.csv,.jpg,.jpeg,.png,.zip,.doc,.docx,.txt" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.length>0&&<ul className="selected-files wide">{files.map((f:File,i:number)=><li key={i}><FileText size={15}/><span>{f.name}</span><small>{number(f.size/1024/1024)} MB</small></li>)}</ul>}{!real.projects.length&&<p className="form-hint wide">Cadastre uma obra antes de importar documentos.</p>}</>}
</div>{formError&&<div className="error-banner" role="alert">{formError}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setModal(null)} disabled={busy}>Cancelar</button><button type="submit" className="primary" disabled={busy}>{busy?'Salvando…':modal?.kind==='documents'?'Importar arquivos':modal?.kind==='measurements'?'Salvar medição':'Salvar cadastro'}</button></div></form></DialogContent></Dialog>}
