"use client";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {money,dateLabel,labels} from '@/lib/obras';
import {Pencil} from 'lucide-react';
import {AccessButton} from './access-ui';
import {contractUnits,alexContractUnits,pedreiroContractUnits,amountUnits,payableUnits,startPercentUnits,endPercentUnits,canEditMeasurement,VALUE_SCALE,PERCENT_SCALE} from '@/lib/measurement';
export function RecordDetails({target,onClose,onEdit,data}:any){
 if(!target)return null;
 const r=target.row;
 const editableMeasurement=target.kind==='measurements'&&canEditMeasurement(data.measurements,r);
 const fields:any={engineers:[['Nome',r.name],['CREA',r.crea],['Especialidade',r.specialty],['E-mail',r.email],['Telefone',r.phone]],teams:[['Equipe',r.name],['Líder',r.leader],['Serviço',r.trade],['Obra',data.projects.find((p:any)=>p.id===r.projectId)?.name],['Integrantes',r.members]],stageTypes:[['Tipo',r.name],['Descrição',r.description]],stages:[['Etapa',r.name],['Obra',data.projects.find((p:any)=>p.id===r.projectId)?.name],['Tipo',data.stageTypes.find((t:any)=>t.id===r.stageTypeId)?.name],['Empreiteira',r.contractor],['MA3 — base de cálculo',money(contractUnits(r)/VALUE_SCALE)],['ALEX — base de cálculo',money(alexContractUnits(r)/VALUE_SCALE)],['Pedreiro — base de cálculo',money(pedreiroContractUnits(r)/VALUE_SCALE)],['Início',dateLabel(r.start)],['Fim',dateLabel(r.end)]],measurements:[['Etapa',r.stageName],['Obra',data.projects.find((p:any)=>p.id===r.projectId)?.name],['Período',dateLabel(r.periodStart)+' a '+dateLabel(r.date)],['Percentual inicial',(startPercentUnits(r)/PERCENT_SCALE).toFixed(4)+'%'],['Percentual acumulado',(endPercentUnits(r)/PERCENT_SCALE).toFixed(4)+'%'],['Valor MA3',money(amountUnits(r)/VALUE_SCALE)],['Total financeiro',money(payableUnits(r)/VALUE_SCALE)],['Situação',r.cancelledAt?'Cancelada':r.paid?'Paga':'Pendente'],['Observações',r.notes]]};
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Consultar {labels[target.kind]}</DialogTitle><DialogDescription>{editableMeasurement?'Confira os dados ou abra este lançamento para edição.':'Informações do cadastro.'}</DialogDescription></DialogHeader><dl className="record-details">{(fields[target.kind]||[]).map(([label,value]:any)=><div key={label}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl><div className="form-actions"><button className="secondary" onClick={onClose}>Fechar</button>{editableMeasurement&&<AccessButton permission="measurements.edit" className="primary" onClick={()=>onEdit('measurements',r)}><Pencil size={16}/>Editar lançamento</AccessButton>}</div></DialogContent></Dialog>
}
