"use client";
import {useState} from 'react';
import {Plus,Pencil,Copy,KeyRound,ShieldCheck} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Choice,Blank} from './obras-ui';
import {modules,presets,expandPermissions} from '@/lib/permissions';
import {dateLabel} from '@/lib/obras';
const roles=[['admin','Administrador'],['engineer','Engenheiro'],['viewer','Consulta'],['custom','Personalizado']];
export function UsersPanel({session,refresh}:any){
 const [editing,setEditing]=useState<any>(null),[form,setForm]=useState<any>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[link,setLink]=useState(''),[expires,setExpires]=useState(''),[query,setQuery]=useState(''),[notice,setNotice]=useState('');
 function start(user?:any){setEditing(user||{});setForm(user?{...user}:{name:'',email:'',role:'viewer',active:true,permissions:[...presets.viewer]});setError('');setNotice('')}
 async function api(body:any,method='POST'){const r=await fetch('/api/users',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível salvar.');return d}
 function showLink(d:any){if(d.activationToken){setLink(location.origin+'/#activate='+encodeURIComponent(d.activationToken));setExpires(d.expires)}}
 async function save(e:any){e.preventDefault();setBusy(true);setError('');try{const d=await api({id:editing.id,revision:editing.revision,data:form},editing.id?'PATCH':'POST');showLink(d);setEditing(null);await refresh();setNotice('Usuário salvo.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function renew(user:any){setBusy(true);setNotice('');try{showLink(await api({action:'renew',id:user.id}));await refresh()}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 function toggle(key:string,on:boolean){let p=on?expandPermissions([...form.permissions,key]):form.permissions.filter((x:string)=>x!==key);if(!on){if(key.endsWith('.view'))p=p.filter((x:string)=>x!==key.replace('.view','.edit'));if(key==='projects.view')p=p.filter((x:string)=>!['stages','measurements','documents','teams','payments'].includes(x.split('.')[0]));if(key==='stageTypes.view')p=p.filter((x:string)=>!['stages','measurements','payments'].includes(x.split('.')[0]));if(key==='stages.view')p=p.filter((x:string)=>!['measurements','payments'].includes(x.split('.')[0]));if(key==='measurements.view')p=p.filter((x:string)=>!['measurements.cancel','payments.edit'].includes(x));if(key==='documents.view')p=p.filter((x:string)=>x!=='documents.delete')}
 setForm({...form,role:'custom',permissions:p})}
 const rows=session.users.filter((u:any)=>(u.name+' '+u.email).toLowerCase().includes(query.toLowerCase()));
 return <><section className="panel"><div className="section-heading"><div><h2>Usuários e permissões</h2><p>Defina o que cada pessoa pode consultar e alterar no sistema.</p></div><button className="primary" onClick={()=>start()}><Plus size={17}/>Novo usuário</button></div><div className="notice">O login é feito com a conta ChatGPT. Libere o e-mail no compartilhamento do site e envie o link de ativação gerado aqui. O link vincula os privilégios à conta que o utilizar e vale por 7 dias.</div><label className="user-search">Buscar usuário<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome ou e-mail"/></label>{notice&&<p role="status" className="notice">{notice}</p>}{rows.length?<Table><TableHeader><TableRow>{['Usuário','Perfil','Situação','Vínculo','Ações'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((u:any)=><TableRow key={u.id}><TableCell><strong>{u.name}</strong><small className="cell-subtitle">{u.email}</small>{u.id==='owner'&&<small className="cell-subtitle">Administrador principal</small>}</TableCell><TableCell>{roles.find(r=>r[0]===u.role)?.[1]}</TableCell><TableCell><span className={'status '+(u.active?'green':'gray')}>{u.active?'Ativo':'Desativado'}</span></TableCell><TableCell>{u.identityId?'Conta vinculada':'Aguardando ativação'}{!u.identityId&&u.activationExpiresAt&&<small className="cell-subtitle">Link até {dateLabel(u.activationExpiresAt)}</small>}</TableCell><TableCell><div className="actions"><button className="icon-button" title={'Editar '+u.name} onClick={()=>start(u)}><Pencil size={17}/></button>{!u.identityId&&u.active&&<button className="secondary" disabled={busy} onClick={()=>renew(u)}><KeyRound size={15}/>Novo link</button>}</div></TableCell></TableRow>)}</TableBody></Table>:<Blank title="Nenhum usuário encontrado" description="Ajuste a busca ou cadastre um usuário." icon={ShieldCheck}/>}</section>
 <Dialog open={!!editing} onOpenChange={v=>{if(!busy&&!v)setEditing(null)}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{editing?.id?'Editar usuário':'Cadastrar usuário'}</DialogTitle><DialogDescription>As permissões se aplicam a todas as obras. Desativar bloqueia o próximo acesso aos dados.</DialogDescription></DialogHeader><form onSubmit={save}><div className="form-grid"><label>Nome<input required maxLength={150} value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>E-mail de contato<input required type="email" maxLength={254} value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Perfil<Choice value={form.role} onChange={(role:string)=>setForm({...form,role,permissions:role==='custom'?form.permissions:presets[role as keyof typeof presets]})} options={editing?.id==='owner'?[roles[0]]:roles} label="Perfil de acesso"/></label><label>Situação<Choice value={form.active?'active':'disabled'} onChange={(v:string)=>setForm({...form,active:v==='active'})} options={editing?.id==='owner'?[['active','Ativo']]:[['active','Ativo'],['disabled','Desativado']]} label="Situação do usuário"/></label></div><div className="permissions-grid"><div className="permissions-head"><strong>Permissão</strong><span>Consultar</span><span>Alterar</span></div>{modules.map(([key,label])=><div className="permissions-row" key={key}><span>{label}</span>{['view','edit'].map(action=><Checkbox key={action} aria-label={label+' — '+(action==='view'?'consultar':'alterar')} checked={(form.permissions||[]).includes(key+'.'+action)} disabled={form.role==='admin'} onCheckedChange={v=>toggle(key+'.'+action,v===true)}/>)}</div>)}{[['payments.edit','Marcar ou alterar pagamentos'],['measurements.cancel','Cancelar medições'],['documents.delete','Excluir documentos'],['users.manage','Administrar usuários e permissões']].map(([key,label])=><label className="permission-extra" key={key}><Checkbox checked={(form.permissions||[]).includes(key)} disabled={form.role==='admin'} onCheckedChange={v=>toggle(key,v===true)}/>{label}</label>)}</div><p className="form-hint">Alterar inclui consultar. Medições também permitem consultar suas etapas e obras; documentos e equipes incluem a consulta das obras vinculadas.</p>{error&&<div role="alert" className="error-banner">{error}</div>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando…':'Salvar usuário'}</button></div></form></DialogContent></Dialog>
 <Dialog open={!!link} onOpenChange={v=>{if(!v)setLink('')}}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Link de ativação</DialogTitle><DialogDescription>Envie este link somente à pessoa cadastrada, depois de liberar o acesso no compartilhamento do site. Ele pode ser usado uma vez e expira em {dateLabel(expires)}.</DialogDescription></DialogHeader><input aria-label="Link de ativação" className="activation-link" readOnly value={link} onFocus={e=>e.target.select()}/><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setNotice('Link copiado.')}catch{setNotice('Selecione e copie o link acima.')}}}><Copy size={17}/>Copiar link</button><p role="status">{notice}</p></DialogContent></Dialog></>;
}
export function AccessPending({session,refresh,setupToken,activationToken}:any){const [token,setToken]=useState(activationToken||setupToken||''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function activate(e:any){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:setupToken?'bootstrap':'activate',token})});const d:any=await r.json();if(!r.ok)throw Error(d.error);history.replaceState(null,'',location.pathname);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <main className="access-pending"><img src="/brand/macchio-logo.png" alt="Macchio Engenharia" width={280}/><section className="panel"><ShieldCheck size={30}/><h1>{session.user&&!session.user.active?'Acesso desativado':setupToken?'Configurar administrador':'Ativar acesso'}</h1><p>{session.identity?.email}</p>{session.user&&!session.user.active?<p>Solicite a reativação ao administrador do sistema.</p>:<form onSubmit={activate}><p>{setupToken?'Confirme a vinculação desta conta como administrador principal.':'Use o código do link enviado pelo administrador para vincular sua conta.'}</p><label>Código de ativação<input required value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><button className="primary" disabled={busy}>{busy?'Verificando…':setupToken?'Vincular administrador':'Ativar acesso'}</button></form>}{error&&<div className="error-banner" role="alert">{error}</div>}<a href="/signout-with-chatgpt?return_to=%2F" target="_top">Entrar com outra conta</a></section></main>}
