import {contractCents,amountCents,normalizeMeasurements,initialStages,weekRange} from './measurement';
export type Row=Record<string,any>;
export type Store={projects:Row[];engineers:Row[];teams:Row[];stages:Row[];measurements:Row[];documents:Row[]};
export const empty:Store={projects:[],engineers:[],teams:[],stages:[],measurements:[],documents:[]};
export const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:2}).format(v||0);
export const number=(v:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(v||0);
export const dateLabel=(v:string)=>v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—';
export const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
export const initials=(s:string)=>s.split(' ').filter(Boolean).slice(0,2).map(s=>s[0]).join('');
export const countMembers=(s:string)=>s.split('\n').filter(s=>s.trim()).length;
export function stats(data:Store,projectId?:string){const stages=data.stages.filter(s=>!projectId||s.projectId===projectId);const measurements=data.measurements.filter(m=>!m.cancelledAt&&(!projectId||m.projectId===projectId));const planned=stages.reduce((t,s)=>t+contractCents(s)/100,0);const measured=measurements.reduce((t,m)=>t+amountCents(m)/100,0);return {planned,measured,progress:planned?Math.min(100,100*measured/planned):0};}
export const categories=['Projeto','Orçamento','Comprovante de pagamento','Contrato','Relatório','Outros'];
export const labels:Record<string,string>={projects:'obra',engineers:'engenheiro',teams:'equipe',stages:'etapa',measurements:'medição',documents:'documento'};
export const demo:Store={
engineers:[{id:'e1',name:'Ana Paula Ribeiro',crea:'5061234567-SP',specialty:'Engenharia Civil',email:'ana@example.com',phone:'(11) 90000-0101'},{id:'e2',name:'Ricardo Mendes',crea:'5067654321-SP',specialty:'Engenharia Civil',email:'ricardo@example.com',phone:'(11) 90000-0102'}],
projects:[{id:'p1',name:'Residencial Villa dos Ipês',client:'Incorporadora Horizonte',address:'Campinas, SP · Jardim das Palmeiras',engineerId:'e1',start:'2026-03-02',end:'2026-12-18',budget:1850000,status:'Em andamento',notes:'Construção residencial com 12 unidades. Conferir os projetos antes de cada etapa.'},{id:'p2',name:'Edifício Comercial Aurora',client:'Aurora Empreendimentos',address:'São Paulo, SP · Vila Mariana',engineerId:'e2',start:'2026-04-06',end:'2027-03-26',budget:3200000,status:'Em andamento',notes:'Edificação comercial. Compatibilização dos projetos de instalações em andamento.'},{id:'p3',name:'Casa Jardim Europa',client:'Cliente demonstrativo',address:'Valinhos, SP · Jardim Europa',engineerId:'e1',start:'2026-07-13',end:'2027-01-29',budget:780000,status:'Planejamento',notes:'Residência unifamiliar. Conferir orçamento e liberar as frentes de trabalho.'}],
teams:[{id:'t1',name:'Equipe Estrutural',leader:'Carlos Nogueira',trade:'Estrutura e alvenaria',members:'Carlos Nogueira\nJoão Silva\nPedro Santos\nLucas Costa\nMarcos Lima\nAndré Oliveira',projectId:'p1'},{id:'t2',name:'Instalações Elétricas',leader:'Eduardo Alves',trade:'Elétrica',members:'Eduardo Alves\nBruno Dias\nFelipe Souza\nJosé Rocha',projectId:'p1'},{id:'t3',name:'Equipe de Acabamento',leader:'Mariana Santos',trade:'Revestimentos',members:'Mariana Santos\nRafael Gomes\nPaulo Freitas\nDaniel Reis\nThiago Lopes',projectId:'p2'}],
stages:[{id:'s1',projectId:'p1',name:'Fundações e estrutura',unit:'m³',quantity:500,price:1400,start:'2026-03-02',end:'2026-06-30'},{id:'s2',projectId:'p1',name:'Alvenaria e vedações',unit:'m²',quantity:2500,price:160,start:'2026-06-01',end:'2026-10-01'},{id:'s3',projectId:'p1',name:'Instalações e acabamento',unit:'vb',quantity:1,price:750000,start:'2026-08-03',end:'2026-12-18'},{id:'s4',projectId:'p2',name:'Estrutura de concreto',unit:'m³',quantity:1600,price:2000,start:'2026-04-06',end:'2027-03-26'},{id:'s5',projectId:'p3',name:'Execução da residência',unit:'vb',quantity:1,price:780000,start:'2026-07-13',end:'2027-01-29'}],
measurements:[{id:'m1',projectId:'p1',stageId:'s1',date:'2026-04-30',quantity:150,unitPrice:1400,notes:'Blocos de fundação.'},{id:'m2',projectId:'p1',stageId:'s1',date:'2026-05-29',quantity:200,unitPrice:1400,notes:'Pavimento térreo.'},{id:'m3',projectId:'p1',stageId:'s1',date:'2026-06-30',quantity:150,unitPrice:1400,notes:'Estrutura concluída.'},{id:'m4',projectId:'p1',stageId:'s2',date:'2026-07-31',quantity:1500,unitPrice:160,notes:'Vedações do térreo e primeiro pavimento.'},{id:'m5',projectId:'p1',stageId:'s2',date:'2026-08-31',quantity:800,unitPrice:160,notes:'Alvenaria do segundo pavimento.'},{id:'m6',projectId:'p1',stageId:'s3',date:'2026-09-10',quantity:.25,unitPrice:750000,notes:'Infraestrutura elétrica e hidráulica.'},{id:'m7',projectId:'p2',stageId:'s4',date:'2026-08-28',quantity:672,unitPrice:2000,notes:'Medição demonstrativa.'},{id:'m8',projectId:'p3',stageId:'s5',date:'2026-09-11',quantity:.12,unitPrice:780000,notes:'Mobilização e serviços preliminares.'}],documents:[]};

demo.stages=demo.projects.flatMap(p=>initialStages.map((name,i)=>({id:p.id+'-etapa-'+i,projectId:p.id,name,unit:'%',quantity:100,price:p.budget/900,contractCents:Math.round(p.budget*100/9),contractor:'Empreiteira demonstrativa',start:p.start,end:p.end})));
const demoWeek=weekRange(today());const beforeWeek=new Date(demoWeek.start+'T12:00:00Z');beforeWeek.setUTCDate(beforeWeek.getUTCDate()-1);const previousDate=beforeWeek.toISOString().slice(0,10);
demo.measurements=[['p1',0,0,30,previousDate,1],['p1',0,30,45,today(),0],['p1',1,0,15,today(),0],['p2',0,0,20,today(),0]].map(([pid,index,previous,current,date,paid],i)=>{const stage=demo.stages.find(s=>s.id===pid+'-etapa-'+index)!;const base=stage.contractCents;return {id:'demo-m'+i,sequence:i,projectId:pid,stageId:stage.id,stageName:stage.name,contractor:stage.contractor,contractCents:base,startBp:Number(previous)*100,endBp:Number(current)*100,amountCents:Math.round(base*Number(current)/100)-Math.round(base*Number(previous)/100),date,periodStart:paid?date:demoWeek.start,paid,paidAt:paid?date:null,paymentHistory:'[]',notes:'Medição demonstrativa.'}});
