import {scrypt,randomBytes,timingSafeEqual} from 'node:crypto';
import {Buffer} from 'node:buffer';
import {database} from './access';
const options={N:32768,r:8,p:3,maxmem:64*1024*1024};
export const validPassword=(value:unknown):value is string=>typeof value==='string'&&/^[0-9]{1,8}$/.test(value);
export const normalizeUsername=(value:string)=>value.trim().toLowerCase();
export const validUsername=(value:string)=>/^[a-z0-9][a-z0-9._@+-]{2,253}$/.test(value);
function derive(password:string,salt:Buffer){return new Promise<Buffer>((resolve,reject)=>scrypt(password,salt,32,options,(error,key)=>error?reject(error):resolve(key)))}
export async function hashPassword(password:string){const salt=randomBytes(16),key=await derive(password,salt);return `scrypt$32768$8$3$${salt.toString('hex')}$${key.toString('hex')}`}
export async function verifyPassword(password:string,hash:string|null){const parts=(hash||'scrypt$32768$8$3$00000000000000000000000000000000$'+'0'.repeat(64)).split('$');if(parts.length!==6||parts[0]!=='scrypt'||parts[1]!=='32768'||parts[2]!=='8'||parts[3]!=='3'||!/^[a-f0-9]{32}$/.test(parts[4])||!/^[a-f0-9]{64}$/.test(parts[5]))return false;const key=await derive(password,Buffer.from(parts[4],'hex'));return timingSafeEqual(key,Buffer.from(parts[5],'hex'))&&!!hash}
export async function tokenHash(token:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));return Buffer.from(digest).toString('hex')}
export function cookieName(request:Request){return new URL(request.url).protocol==='https:'?'__Host-macchio_session':'macchio_session'}
export function sessionToken(request:Request){const name=cookieName(request)+'=';return (request.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name))?.slice(name.length)||''}
export function sessionCookie(request:Request,token:string){return `${cookieName(request)}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${token?34560000:0}${new URL(request.url).protocol==='https:'?'; Secure':''}`}
export async function createSession(request:Request,user:any){const token=randomBytes(32).toString('hex'),hash=await tokenHash(token);const r=await database().prepare('INSERT INTO authSessions(id,userId,authVersion,createdAt) SELECT ?,id,authVersion,? FROM appUsers WHERE id=? AND active=1 AND authVersion=? AND passwordHash IS NOT NULL RETURNING id').bind(hash,new Date().toISOString(),user.id,user.authVersion).all();if(!r.results.length)throw Response.json({error:'O acesso foi atualizado. Entre novamente.'},{status:401});return sessionCookie(request,token)}
export async function loginThrottle(request:Request,username:string){const db=database(),now=Date.now(),window=900000;const keys=[['ip:'+ (request.headers.get('cf-connecting-ip')||'local'),60],['user:'+username,10]] as const;for(const [key,limit] of keys){const hash=await tokenHash(key);const result=await db.prepare('INSERT INTO loginThrottle(id,startedAt,attempts) VALUES(?,?,1) ON CONFLICT(id) DO UPDATE SET attempts=CASE WHEN startedAt<=? THEN 1 ELSE attempts+1 END,startedAt=CASE WHEN startedAt<=? THEN ? ELSE startedAt END RETURNING attempts').bind(hash,now,now-window,now-window,now).first<any>();if(result.attempts>limit)throw Response.json({error:'Muitas tentativas de acesso. Aguarde 15 minutos e tente novamente.'},{status:429,headers:{'Retry-After':'900'}})}await db.prepare('DELETE FROM loginThrottle WHERE startedAt<?').bind(now-86400000).run()}
