import {sql} from 'drizzle-orm';
import {sqliteTable,text,real,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const appUsers=sqliteTable('appUsers',{id:text('id').primaryKey(),username:text('username').unique(),passwordHash:text('passwordHash'),authVersion:integer('authVersion').notNull().default(0),deletedAt:text('deletedAt'),identityId:text('identityId').unique(),name:text('name').notNull(),email:text('email').notNull().unique(),role:text('role').notNull(),active:integer('active').notNull().default(1),permissions:text('permissions').notNull().default('[]'),activationHash:text('activationHash').unique(),activationExpiresAt:text('activationExpiresAt'),revision:integer('revision').notNull().default(0),createdAt:text('createdAt').notNull(),updatedAt:text('updatedAt').notNull()},t=>[uniqueIndex('idx_appUsers_login').on(sql`CASE WHEN ${t.username} IS NULL THEN ${t.email} ELSE ${t.username} END`)]);
export const userAudit=sqliteTable('userAudit',{id:text('id').primaryKey(),userId:text('userId').notNull().references(()=>appUsers.id),actorId:text('actorId').notNull().references(()=>appUsers.id),action:text('action').notNull(),createdAt:text('createdAt').notNull()},t=>[index('idx_userAudit_user').on(t.userId)]);
export const stageTypes=sqliteTable('stageTypes',{id:text('id').primaryKey(),name:text('name').notNull(),nameKey:text('nameKey').notNull().unique(),description:text('description').notNull().default('')});
export const engineers=sqliteTable('engineers',{id:text('id').primaryKey(),name:text('name').notNull(),crea:text('crea').notNull(),specialty:text('specialty').notNull(),email:text('email').notNull(),phone:text('phone').notNull()});
export const projects=sqliteTable('projects',{id:text('id').primaryKey(),name:text('name').notNull(),client:text('client').notNull(),address:text('address').notNull(),engineerId:text('engineerId').references(()=>engineers.id),start:text('start').notNull(),end:text('end').notNull(),stagesInitialized:integer('stagesInitialized').notNull().default(0),budget:real('budget').notNull(),budgetUnits:integer('budgetUnits'),status:text('status').notNull(),notes:text('notes').notNull()});
export const teams=sqliteTable('teams',{id:text('id').primaryKey(),name:text('name').notNull(),leader:text('leader').notNull(),trade:text('trade').notNull(),members:text('members').notNull(),projectId:text('projectId').references(()=>projects.id)},t=>[index('idx_teams_project').on(t.projectId)]);
export const stages=sqliteTable('stages',{id:text('id').primaryKey(),stageTypeId:text('stageTypeId').references(()=>stageTypes.id),projectId:text('projectId').notNull().references(()=>projects.id),name:text('name').notNull(),contractCents:integer('contractCents'),contractUnits:integer('contractUnits'),contractor:text('contractor').notNull().default(''),unit:text('unit').notNull(),quantity:real('quantity').notNull(),price:real('price').notNull(),start:text('start').notNull(),end:text('end').notNull()},t=>[index('idx_stages_project').on(t.projectId)]);
export const measurements=sqliteTable('measurements',{id:text('id').primaryKey(),projectId:text('projectId').notNull().references(()=>projects.id),stageId:text('stageId').notNull().references(()=>stages.id),periodStart:text('periodStart'),startBp:integer('startBp'),endBp:integer('endBp'),startP4:integer('startP4'),endP4:integer('endP4'),amountCents:integer('amountCents'),contractCents:integer('contractCents'),amountUnits:integer('amountUnits'),contractUnits:integer('contractUnits'),stageName:text('stageName').notNull().default(''),contractor:text('contractor').notNull().default(''),paid:integer('paid').notNull().default(0),paidAt:text('paidAt'),paymentHistory:text('paymentHistory').notNull().default('[]'),editHistory:text('editHistory').notNull().default('[]'),allocations:text('allocations'),revision:integer('revision').notNull().default(0),cancelledAt:text('cancelledAt'),createdAt:text('createdAt'),date:text('date').notNull(),quantity:real('quantity').notNull(),unitPrice:real('unitPrice').notNull(),notes:text('notes').notNull()},t=>[index('idx_measurements_stage').on(t.stageId),index('idx_measurements_project').on(t.projectId)]);
export const documents=sqliteTable('documents',{id:text('id').primaryKey(),projectId:text('projectId').notNull().references(()=>projects.id),name:text('name').notNull(),category:text('category').notNull(),size:integer('size').notNull(),mime:text('mime').notNull(),key:text('key').notNull(),created:text('created').notNull()},t=>[index('idx_documents_project').on(t.projectId)]);

export const authSessions=sqliteTable('authSessions',{id:text('id').primaryKey(),userId:text('userId').notNull().references(()=>appUsers.id),authVersion:integer('authVersion').notNull(),createdAt:text('createdAt').notNull()},t=>[index('idx_authSessions_user').on(t.userId)]);
export const loginThrottle=sqliteTable('loginThrottle',{id:text('id').primaryKey(),startedAt:integer('startedAt').notNull(),attempts:integer('attempts').notNull()},t=>[index('idx_loginThrottle_start').on(t.startedAt)]);

export const systemSettings=sqliteTable('systemSettings',{id:text('id').primaryKey(),value:text('value').notNull()});
