import {requireUser} from '@/db/users';
import {env} from 'cloudflare:workers';
import {authorize,database,failure,invalid} from '@/db/access';
const categories=['Projeto','Orçamento','Comprovante de pagamento','Contrato','Relatório','Outros'];
const extensions=['pdf','dwg','dxf','ifc','xlsx','xls','csv','jpg','jpeg','png','zip','doc','docx','txt'];
export async function POST(request:Request){try{await requireUser(request,'documents.edit');if(Number(request.headers.get('content-length'))>26*1024*1024)return invalid('O limite é de 25 MB por arquivo.');const form=await request.formData();const file=form.get('file');const projectId=form.get('projectId');const category=form.get('category');if(!(file instanceof File)||typeof projectId!=='string'||typeof category!=='string'||!categories.includes(category))return invalid('Selecione arquivo, obra e categoria.');if(file.size>25*1024*1024||file.size===0)return invalid('Selecione um arquivo de até 25 MB, com conteúdo.');const ext=file.name.split('.').pop()?.toLowerCase()||'';if(!extensions.includes(ext))return invalid('Formato não permitido. Use PDF, arquivos de projeto, planilhas, documentos, imagens ou ZIP.');const db=database();if(!await db.prepare('SELECT id FROM projects WHERE id=?').bind(projectId).first())return invalid('Obra não encontrada.');if(!env.BUCKET)throw new Error('R2 indisponível');const id=crypto.randomUUID(),key=`documents/${projectId}/${id}`;const mime=ext==='pdf'?'application/pdf':['jpg','jpeg'].includes(ext)?'image/jpeg':ext==='png'?'image/png':'application/octet-stream';const name=file.name.replace(/[\r\n\/\\]/g,'_').slice(0,240);await env.BUCKET.put(key,file.stream(),{httpMetadata:{contentType:mime}});try{await db.prepare('INSERT INTO documents(id,projectId,name,category,size,mime,key,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,projectId,name,category,file.size,mime,key,new Date().toISOString()).run();}catch(e){await env.BUCKET.delete(key);throw e;}return Response.json({id},{status:201});}catch(e){return failure(e)}}
export async function GET(request:Request){try{await requireUser(request,'documents.view');const url=new URL(request.url),id=url.searchParams.get('id');if(!id)return invalid('Documento inválido.');const doc:any=await database().prepare('SELECT * FROM documents WHERE id=?').bind(id).first();if(!doc)return invalid('Documento não encontrado.',404);const object=await env.BUCKET?.get(doc.key);if(!object)return invalid('Arquivo não disponível.',404);const inline=!url.searchParams.has('download')&&['application/pdf','image/jpeg','image/png'].includes(doc.mime);return new Response(object.body,{headers:{'Content-Type':doc.mime,'Content-Length':String(doc.size),'Content-Disposition':`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(doc.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){return failure(e)}}
export async function DELETE(request:Request){try{await requireUser(request,'documents.delete');const {id}=await request.json() as {id:unknown};if(typeof id!=='string')return invalid('Documento inválido.');const db=database();const doc:any=await db.prepare('SELECT key FROM documents WHERE id=?').bind(id).first();if(!doc)return invalid('Documento não encontrado.',404);if(!env.BUCKET)throw new Error('R2 indisponível');await db.prepare('DELETE FROM documents WHERE id=?').bind(id).run();try{await env.BUCKET.delete(doc.key);}catch(e){console.error('Falha ao limpar arquivo sem vínculo',e)}return Response.json({ok:true});}catch(e){return failure(e)}}


export async function PATCH(request:Request){try{await requireUser(request,'documents.edit');const body:any=await request.json();if(typeof body.id!=='string'||typeof body.name!=='string'||!body.name.trim()||body.name.length>240||!categories.includes(body.category)||typeof body.projectId!=='string')return invalid('Confira nome, obra e categoria.');const db=database();if(!await db.prepare('SELECT id FROM projects WHERE id=?').bind(body.projectId).first())return invalid('Obra não encontrada.');const result=await db.prepare('UPDATE documents SET name=?,category=?,projectId=? WHERE id=? RETURNING id').bind(body.name.trim().replace(/[\r\n\/\\]/g,'_'),body.category,body.projectId,body.id).all();if(!result.results.length)return invalid('Documento não encontrado.',404);return Response.json({id:body.id})}catch(e){return failure(e)}}
